/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.staff;

import gui.staff.*;
import entity.Staff;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JFrame;
import enums.TabMenu;
import gui.login.LoginForm;
import javax.swing.JPanel;
import util.CurrentStaff;

/**
 *
 * @author Hoang
 */
public class MenuManager_NV extends javax.swing.JFrame {
    
    private TAB_BanVe tabBanVe;
    private TAB_CaNhan_NV tabCaNhan;
    private TabMenu currentTab;

    /**
     * Creates new form MenuManager
     */
    public MenuManager_NV() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        tabBanVe = new TAB_BanVe();
        tabCaNhan = new TAB_CaNhan_NV();
        menuSwitch(tabBanVe, TabMenu.TAB_BANVE, mnPhimChieu);
        currentTab = TabMenu.TAB_PHIM;
        Staff staff = CurrentStaff.getStaff();
        txtStaff.setText(staff.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLeft = new javax.swing.JPanel();
        logo = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        mnCaNhan = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        mnDangXuat = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        mnPhimChieu = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        pnRight = new javax.swing.JPanel();
        pnTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtStaff = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnLeft.setBackground(new java.awt.Color(20, 38, 66));
        pnLeft.setPreferredSize(new java.awt.Dimension(340, 1030));
        pnLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnLeftMouseClicked(evt);
            }
        });
        pnLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setBackground(new java.awt.Color(20, 38, 66));
        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logo.setPreferredSize(new java.awt.Dimension(268, 60));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Galaxy Cinema");

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-galaxy-60.png"))); // NOI18N

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnLeft.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 100));

        mnCaNhan.setBackground(new java.awt.Color(20, 38, 66));
        mnCaNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnCaNhan.setPreferredSize(new java.awt.Dimension(268, 55));
        mnCaNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnCaNhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnCaNhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnCaNhanMouseExited(evt);
            }
        });

        jLabel72.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Thông tin cá nhân");

        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-user-70.png"))); // NOI18N

        javax.swing.GroupLayout mnCaNhanLayout = new javax.swing.GroupLayout(mnCaNhan);
        mnCaNhan.setLayout(mnCaNhanLayout);
        mnCaNhanLayout.setHorizontalGroup(
            mnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnCaNhanLayout.createSequentialGroup()
                .addComponent(jLabel73)
                .addGap(37, 37, 37)
                .addComponent(jLabel72, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );
        mnCaNhanLayout.setVerticalGroup(
            mnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnCaNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnLeft.add(mnCaNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 340, 80));

        mnDangXuat.setBackground(new java.awt.Color(20, 38, 66));
        mnDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnDangXuat.setPreferredSize(new java.awt.Dimension(268, 55));
        mnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnDangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnDangXuatMouseExited(evt);
            }
        });

        jLabel74.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Đăng xuất");

        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-logout-60 (1).png"))); // NOI18N

        javax.swing.GroupLayout mnDangXuatLayout = new javax.swing.GroupLayout(mnDangXuat);
        mnDangXuat.setLayout(mnDangXuatLayout);
        mnDangXuatLayout.setHorizontalGroup(
            mnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnDangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel75)
                .addGap(40, 40, 40)
                .addComponent(jLabel74, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        mnDangXuatLayout.setVerticalGroup(
            mnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnDangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel75, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabel74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnLeft.add(mnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 340, 80));

        mnPhimChieu.setBackground(new java.awt.Color(11, 77, 163));
        mnPhimChieu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnPhimChieu.setPreferredSize(new java.awt.Dimension(268, 55));
        mnPhimChieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnPhimChieuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnPhimChieuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnPhimChieuMouseExited(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Phim đang chiếu ");

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-movie-60.png"))); // NOI18N

        javax.swing.GroupLayout mnPhimChieuLayout = new javax.swing.GroupLayout(mnPhimChieu);
        mnPhimChieu.setLayout(mnPhimChieuLayout);
        mnPhimChieuLayout.setHorizontalGroup(
            mnPhimChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnPhimChieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51)
                .addGap(40, 40, 40)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mnPhimChieuLayout.setVerticalGroup(
            mnPhimChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnPhimChieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnPhimChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnLeft.add(mnPhimChieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 340, 80));

        getContentPane().add(pnLeft, java.awt.BorderLayout.WEST);

        pnRight.setLayout(new java.awt.BorderLayout());

        pnTop.setBackground(new java.awt.Color(20, 38, 66));
        pnTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-user-50.png"))); // NOI18N
        pnTop.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, -1, 100));

        txtStaff.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        txtStaff.setForeground(new java.awt.Color(255, 255, 255));
        txtStaff.setText("txtStaff");
        pnTop.add(txtStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, -1, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-menu-vertical-26.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnTop.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 6, -1, 90));

        pnRight.add(pnTop, java.awt.BorderLayout.NORTH);

        pnContent.setBackground(new java.awt.Color(255, 255, 255));
        pnContent.setLayout(new java.awt.BorderLayout());
        pnRight.add(pnContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnRight, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void menuSwitch(JPanel panelChuyen, TabMenu tabMoi, JPanel panelTab) {
//        Component oldCom;
        if (currentTab == tabMoi) {
            return;
        }
        mnCaNhan.setBackground(new Color(20, 38, 66));
        mnDangXuat.setBackground(new Color(20, 38, 66));
        mnPhimChieu.setBackground(new Color(20, 38, 66));
        panelTab.setBackground(new Color(11, 77, 163));
        currentTab = tabMoi;
        pnContent.removeAll();
        pnContent.add(panelChuyen, BorderLayout.CENTER);
        pnContent.revalidate();
        pnContent.repaint();
    }


    private void mnCaNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnCaNhanMouseEntered
        // TODO add your handling code here:
        mnCaNhan.setBackground(new Color(11, 77, 163));
    }//GEN-LAST:event_mnCaNhanMouseEntered

    private void mnCaNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnCaNhanMouseExited
        // TODO add your handling code here:

        if (!currentTab.equals(TabMenu.TAB_CANHAN_QL))
            mnCaNhan.setBackground(new Color(20, 38, 66));
    }//GEN-LAST:event_mnCaNhanMouseExited

    private void mnDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDangXuatMouseEntered
        // TODO add your handling code here:
        mnDangXuat.setBackground(new Color(11, 77, 163));
    }//GEN-LAST:event_mnDangXuatMouseEntered

    private void mnDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDangXuatMouseExited
        // TODO add your handling code here:
        mnDangXuat.setBackground(new Color(20, 38, 66));
    }//GEN-LAST:event_mnDangXuatMouseExited

    private void pnLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLeftMouseClicked
        // TODO add your handling code here:  
    }//GEN-LAST:event_pnLeftMouseClicked

    private void mnCaNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnCaNhanMouseClicked
        // TODO add your handling code here:
        menuSwitch(tabCaNhan, TabMenu.TAB_CANHAN_QL, mnCaNhan);
    }//GEN-LAST:event_mnCaNhanMouseClicked

    private void mnDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDangXuatMouseClicked
        // TODO add your handling code here:
        CurrentStaff.setStaff(null);
        this.setVisible(false);
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_mnDangXuatMouseClicked

    private void mnPhimChieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnPhimChieuMouseClicked
        // TODO add your handling code here:
        menuSwitch(tabBanVe, TabMenu.TAB_BANVE, mnPhimChieu);
    }//GEN-LAST:event_mnPhimChieuMouseClicked

    private void mnPhimChieuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnPhimChieuMouseEntered
        // TODO add your handling code here:
        mnPhimChieu.setBackground(new Color(11, 77, 163));
    }//GEN-LAST:event_mnPhimChieuMouseEntered

    private void mnPhimChieuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnPhimChieuMouseExited
        // TODO add your handling code here:
        if (!currentTab.equals(TabMenu.TAB_BANVE))
            mnPhimChieu.setBackground(new Color(20, 38, 66));
    }//GEN-LAST:event_mnPhimChieuMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuManager_NV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuManager_NV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuManager_NV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuManager_NV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuManager_NV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JPanel logo;
    private javax.swing.JPanel mnCaNhan;
    private javax.swing.JPanel mnDangXuat;
    private javax.swing.JPanel mnPhimChieu;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnRight;
    private javax.swing.JPanel pnTop;
    private javax.swing.JLabel txtStaff;
    // End of variables declaration//GEN-END:variables
}
