/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.staff;

import gui.manager.*;
import bus.StaffBUS;
import connectDB.ConnectDB;
import entity.Staff;
import enums.Role;
import gui.custom.CustomComboBoxUI;
import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import util.CurrentStaff;

/**
 *
 * @author daoducdanh
 */
public class TAB_CaNhan_NV extends javax.swing.JPanel {

    /**
     * Creates new form TAB_CANHAN_QL
     */
    private StaffBUS staffBUS;
    private Staff staff = CurrentStaff.getStaff();
    public TAB_CaNhan_NV() {
        staffBUS = new StaffBUS();
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnRight = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        cbbGT = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        txtChucVu = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jDateNVL = new com.toedter.calendar.JDateChooser();
        txtMKMoi = new javax.swing.JPasswordField();
        txtNLMKMoi = new javax.swing.JPasswordField();
        txtMKCu = new javax.swing.JPasswordField();
        jLabel76 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setMinimumSize(new java.awt.Dimension(1083, 765));
        pnRight.setPreferredSize(new java.awt.Dimension(1083, 765));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel42.setText("Họ và tên:");

        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtTen.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        cbbGT.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cbbGT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbbGT.setUI(new CustomComboBoxUI());
        cbbGT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel43.setText("Thông tin cá nhân");

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel44.setText("Số điện thoại:");

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel45.setText("Mật khẩu cũ:");

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel46.setText("Email:");

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel47.setText("Tài khoản đăng nhập:");

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtSDT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        txtChucVu.setEditable(false);
        txtChucVu.setEnabled(false);
        txtChucVu.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        btnLuu.setBackground(new java.awt.Color(11, 77, 163));
        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Lưu");
        btnLuu.setBorder(null);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel48.setText("Chức vụ:");

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel49.setText("Thông tin cơ bản:");

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel50.setText("Mật khẩu mới:");

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel58.setText("Nhập lại mật khẩu:");

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel59.setText("Tài khoản:");

        txtTK.setEditable(false);
        txtTK.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtTK.setEnabled(false);

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel60.setText("Ngày vào làm");

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel61.setText("Mã nhân viên:");

        txtMa.setEditable(false);
        txtMa.setEnabled(false);
        txtMa.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jDateNVL.setBackground(new java.awt.Color(255, 255, 255));
        jDateNVL.setEnabled(false);
        jDateNVL.setBorder(new javax.swing.border.MatteBorder(null));
        jDateNVL.setDateFormatString("dd/MM/yyyy");
        jDateNVL.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtMKMoi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtNLMKMoi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtMKCu.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jLabel76.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel76.setText("Giới tính:");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtEmail.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        javax.swing.GroupLayout pnRightLayout = new javax.swing.GroupLayout(pnRight);
        pnRight.setLayout(pnRightLayout);
        pnRightLayout.setHorizontalGroup(
            pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(610, 610, 610)
                .addComponent(jLabel43))
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel49))
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel61)
                .addGap(336, 336, 336)
                .addComponent(jLabel60))
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jDateNVL, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel42)
                .addGap(373, 373, 373)
                .addComponent(jLabel44))
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel76)
                .addGap(382, 382, 382)
                .addComponent(jLabel48))
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(cbbGT, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel46))
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel47))
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel59)
                .addGap(122, 122, 122)
                .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel45)
                .addGap(97, 97, 97)
                .addComponent(txtMKCu, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel50)
                .addGap(82, 82, 82)
                .addComponent(txtMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel58)
                .addGap(40, 40, 40)
                .addComponent(txtNLMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(1100, 1100, 1100)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnRightLayout.setVerticalGroup(
            pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel43)
                .addGap(16, 16, 16)
                .addComponent(jLabel49)
                .addGap(14, 14, 14)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel61)
                    .addComponent(jLabel60))
                .addGap(13, 13, 13)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateNVL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel44))
                .addGap(13, 13, 13)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel76)
                    .addComponent(jLabel48))
                .addGap(13, 13, 13)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbGT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel46)
                .addGap(13, 13, 13)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel47)
                .addGap(24, 24, 24)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRightLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel59))
                    .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRightLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel45))
                    .addComponent(txtMKCu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRightLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel50))
                    .addComponent(txtMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRightLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel58))
                    .addComponent(txtNLMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        txtMKMoi.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        txtNLMKMoi.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        txtMKCu.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 1610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void loadData() {
        txtMa.setText(staff.getStaffId());
        txtTen.setText(staff.getName());
        txtTK.setText(staff.getUsername());
        txtSDT.setText(staff.getPhone());
        txtChucVu.setText(staff.getRole().toString());
        txtEmail.setText(staff.getEmail());
        if (staff.isGender() == true) {
            cbbGT.setSelectedItem("Nam");
        } else {
            cbbGT.setSelectedItem("Nữ");
        }
        Date nvl = Date.from(staff.getStartingDate().atStartOfDay(ZoneId.systemDefault()).toInstant());
        jDateNVL.setDate(nvl);
    }
    private boolean validData() {
        String tenNV = txtTen.getText().trim();
        Date dateNVL = jDateNVL.getDate();
        if (dateNVL == null) {
            JOptionPane.showMessageDialog(this, "Error: Ngày vào làm không được để trống!");
            jDateNVL.requestFocus();
            return false;
        } else {
            LocalDate lcdateNVL = dateNVL.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            if (lcdateNVL.isAfter(LocalDate.now())) {
                JOptionPane.showMessageDialog(this, "Error: Ngày vào làm phải trước hoặc là ngày hiện tại!");
                jDateNVL.requestFocus();
                return false;
            }
        }
        String sdt = txtSDT.getText().trim();
        String email = txtEmail.getText().trim();
        String mkMoi = new String(txtMKMoi.getPassword());
        String mkCu = new String(txtMKCu.getPassword());
        String nlMKMoi = new String(txtNLMKMoi.getPassword());

        if (!(tenNV.matches("^[A-Z][a-z]+(\\s[A-Z][a-z]+)+$"))) {
            JOptionPane.showMessageDialog(this, "Error: Họ và tên phải có ít nhất 2 từ trở lên, mỗi từ phải bắt đầu bằng chữ HOA!",
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtTen.requestFocus();
            return false;
        }

        if (!(sdt.matches("^(03|05|07|08|09)\\d{8}$"))) {
            JOptionPane.showMessageDialog(this, "Error: Số điện thoại phải đủ 10 số và bắt đầu bằng 03, 05, 07, 08 hoặc 09!",
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtSDT.requestFocus();
            return false;
        }

        if (!(email.matches("^[a-zA-Z0-9]+@[a-zA-Z]+\\.com$"))) {
            JOptionPane.showMessageDialog(this, "Error: Email không đúng định dạng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtEmail.requestFocus();
            return false;
        }
        if (!(mkCu.trim().equals("") || mkMoi.trim().equals("") || nlMKMoi.trim().equals(""))) {
            if (!(mkMoi.matches("^(?=.*[0-9])(?=.*[A-Z])(?=.*[!@#$%^&*()]).{6,}$"))) {
                JOptionPane.showMessageDialog(this, "Error: Mật khẩu mới phải có từ 6 ký tự trở lên, có ít nhất 1 ký tự số, 1 ký tự in hoa, 1 ký tự đặc biệt!",
                        "Lỗi", JOptionPane.ERROR_MESSAGE);
                txtMKMoi.requestFocus();
                return false;
            }
        }

        return true;
    }
    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if (validData() == true) {
            String mkCu = new String(txtMKCu.getPassword());
            String mkMoi = new String(txtMKMoi.getPassword());
            String nlMKMoi = new String(txtNLMKMoi.getPassword());
            if (mkCu.trim().equals("") && mkMoi.equals("") && nlMKMoi.trim().equals("")) {
                String maNV = txtMa.getText().trim();
                String tenNV = txtTen.getText().trim();
                boolean gt = cbbGT.getSelectedItem().equals("Nam");
                Date dateNVL = jDateNVL.getDate();
                LocalDate lcdateNVL = dateNVL.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                String sdt = txtSDT.getText().trim();
                Role role = staff.getRole();
                String email = txtEmail.getText().trim();
                String username = staff.getUsername();
                String password = staff.getPassword();
                Staff st = new Staff(maNV, tenNV, username, password, sdt, gt, lcdateNVL, role, email);
                boolean check = staffBUS.updateStaff(st);
                if (check == true) {
                    CurrentStaff.setStaff(st);
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } else if (!(mkCu.trim().equals("") || mkMoi.trim().equals("") || nlMKMoi.trim().equals(""))) {
                String mkht = staff.getPassword().trim();
                if (!(mkCu.trim().equals(mkht))) {
                    JOptionPane.showMessageDialog(this, "Mật khẩu cũ không chính xác!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    txtMKCu.requestFocus();
                } else if (!(mkMoi.trim().equals(nlMKMoi.trim()))) {
                    JOptionPane.showMessageDialog(this, "Mật khẩu nhập lại không chính xác!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    txtNLMKMoi.requestFocus();
                } else {
                    String maNV = txtMa.getText().trim();
                    String tenNV = txtTen.getText().trim();
                    boolean gt;
                    if (cbbGT.getSelectedItem().equals("Nam")) {
                        gt = true;
                    } else {
                        gt = false;
                    }
                    Date dateNVL = jDateNVL.getDate();
                    LocalDate lcdateNVL = dateNVL.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                    String sdt = txtSDT.getText().trim();
                    Role role = staff.getRole();
                    String email = txtEmail.getText().trim();
                    String username = staff.getUsername();
                    String password = mkMoi.trim();
                    Staff st = new Staff(maNV, tenNV, username, password, sdt, gt, lcdateNVL, role, email);
                    boolean check = staffBUS.updateStaff(st);
                    if (check == true) {
                        CurrentStaff.setStaff(st);
                        JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                        txtMKCu.setText("");
                        txtMKMoi.setText("");
                        txtNLMKMoi.setText("");
                    } else {
                        JOptionPane.showMessageDialog(this, "Cập nhật thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ phần mật khẩu nếu muốn đổi mật khẩu, nếu không đổi vui lòng để trống!",
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JComboBox<String> cbbGT;
    private com.toedter.calendar.JDateChooser jDateNVL;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JPanel pnRight;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtMKCu;
    private javax.swing.JPasswordField txtMKMoi;
    private javax.swing.JTextField txtMa;
    private javax.swing.JPasswordField txtNLMKMoi;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTK;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
