/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.manager;

import entity.Staff;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JFrame;
import enums.TabMenu;
import gui.login.LoginForm;
import javax.swing.JPanel;
import util.CurrentStaff;

/**
 *
 * @author Hoang
 */
public class MenuManager_QL extends javax.swing.JFrame {

    private TAB_HoaDon tabHoaDon;
    private TAB_Voucher tabVoucher;
    private TAB_ThongKe tabThongKe;
    private TAB_SuatChieu tabSuatChieu;
    private TAB_SanPham tabSanPham;
    private TAB_Phong tabPhong;
    private TAB_Phim tabPhim;
    private TAB_NhanSu tabNhanSu;
    private TAB_KhachHang tabKhachHang;
    private TAB_CaNhan_QL tabCaNhan;
    private TabMenu currentTab;

    /**
     * Creates new form MenuManager
     */
    public MenuManager_QL() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        tabHoaDon = new TAB_HoaDon();
        tabVoucher = new TAB_Voucher();
        tabThongKe = new TAB_ThongKe();
        tabSuatChieu = new TAB_SuatChieu();
        tabSanPham = new TAB_SanPham();
        tabPhong = new TAB_Phong();
        tabPhim = new TAB_Phim();
        tabNhanSu = new TAB_NhanSu();
        tabKhachHang = new TAB_KhachHang();
        tabCaNhan = new TAB_CaNhan_QL();
        menuSwitch(tabPhim, TabMenu.TAB_PHIM, mnQLPhim);
        currentTab = TabMenu.TAB_PHIM;
        Staff staff = CurrentStaff.getStaff();
        txtStaff.setText(staff.getName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLeft = new javax.swing.JPanel();
        logo = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        mnQLPhim = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        mnQLSuatChieu = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        mnQLNhanSu = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        mnQLSanPham = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        mnQLKhachHang = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        mnQLPhong = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        mnHoaDon = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        mnVoucher = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        mnThongke = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        mnCaNhan = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        mnDangXuat = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        pnRight = new javax.swing.JPanel();
        pnTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtStaff = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnLeft.setBackground(new java.awt.Color(20, 38, 66));
        pnLeft.setPreferredSize(new java.awt.Dimension(340, 1030));
        pnLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnLeftMouseClicked(evt);
            }
        });

        logo.setBackground(new java.awt.Color(20, 38, 66));
        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logo.setPreferredSize(new java.awt.Dimension(268, 60));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Galaxy Cinema");

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-galaxy-60.png"))); // NOI18N

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mnQLPhim.setBackground(new java.awt.Color(20, 38, 66));
        mnQLPhim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnQLPhim.setPreferredSize(new java.awt.Dimension(268, 55));
        mnQLPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnQLPhimMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnQLPhimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnQLPhimMouseExited(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Quản lý phim");

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-movie-60.png"))); // NOI18N

        javax.swing.GroupLayout mnQLPhimLayout = new javax.swing.GroupLayout(mnQLPhim);
        mnQLPhim.setLayout(mnQLPhimLayout);
        mnQLPhimLayout.setHorizontalGroup(
            mnQLPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnQLPhimLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51)
                .addGap(40, 40, 40)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        mnQLPhimLayout.setVerticalGroup(
            mnQLPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnQLPhimLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnQLPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mnQLSuatChieu.setBackground(new java.awt.Color(20, 38, 66));
        mnQLSuatChieu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnQLSuatChieu.setPreferredSize(new java.awt.Dimension(268, 55));
        mnQLSuatChieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnQLSuatChieuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnQLSuatChieuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnQLSuatChieuMouseExited(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Quản lý suất chiếu");

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-suatchieu.png"))); // NOI18N

        javax.swing.GroupLayout mnQLSuatChieuLayout = new javax.swing.GroupLayout(mnQLSuatChieu);
        mnQLSuatChieu.setLayout(mnQLSuatChieuLayout);
        mnQLSuatChieuLayout.setHorizontalGroup(
            mnQLSuatChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnQLSuatChieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel53)
                .addGap(40, 40, 40)
                .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        mnQLSuatChieuLayout.setVerticalGroup(
            mnQLSuatChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnQLSuatChieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnQLSuatChieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mnQLNhanSu.setBackground(new java.awt.Color(20, 38, 66));
        mnQLNhanSu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnQLNhanSu.setPreferredSize(new java.awt.Dimension(268, 55));
        mnQLNhanSu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnQLNhanSuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnQLNhanSuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnQLNhanSuMouseExited(evt);
            }
        });

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Quản lý nhân sự");

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-group-60.png"))); // NOI18N

        javax.swing.GroupLayout mnQLNhanSuLayout = new javax.swing.GroupLayout(mnQLNhanSu);
        mnQLNhanSu.setLayout(mnQLNhanSuLayout);
        mnQLNhanSuLayout.setHorizontalGroup(
            mnQLNhanSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnQLNhanSuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel55)
                .addGap(40, 40, 40)
                .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        mnQLNhanSuLayout.setVerticalGroup(
            mnQLNhanSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnQLNhanSuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnQLNhanSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mnQLSanPham.setBackground(new java.awt.Color(20, 38, 66));
        mnQLSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnQLSanPham.setPreferredSize(new java.awt.Dimension(268, 55));
        mnQLSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnQLSanPhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnQLSanPhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnQLSanPhamMouseExited(evt);
            }
        });

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Quản lý sản phẩm");

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-hamburger-60 (1).png"))); // NOI18N

        javax.swing.GroupLayout mnQLSanPhamLayout = new javax.swing.GroupLayout(mnQLSanPham);
        mnQLSanPham.setLayout(mnQLSanPhamLayout);
        mnQLSanPhamLayout.setHorizontalGroup(
            mnQLSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnQLSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel57)
                .addGap(40, 40, 40)
                .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        mnQLSanPhamLayout.setVerticalGroup(
            mnQLSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnQLSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnQLSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mnQLKhachHang.setBackground(new java.awt.Color(20, 38, 66));
        mnQLKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnQLKhachHang.setPreferredSize(new java.awt.Dimension(268, 55));
        mnQLKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnQLKhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnQLKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnQLKhachHangMouseExited(evt);
            }
        });

        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Quản lý khách hàng");

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-user-groups-60.png"))); // NOI18N

        javax.swing.GroupLayout mnQLKhachHangLayout = new javax.swing.GroupLayout(mnQLKhachHang);
        mnQLKhachHang.setLayout(mnQLKhachHangLayout);
        mnQLKhachHangLayout.setHorizontalGroup(
            mnQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnQLKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel63)
                .addGap(40, 40, 40)
                .addComponent(jLabel62, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        mnQLKhachHangLayout.setVerticalGroup(
            mnQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnQLKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabel62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mnQLPhong.setBackground(new java.awt.Color(20, 38, 66));
        mnQLPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnQLPhong.setPreferredSize(new java.awt.Dimension(268, 55));
        mnQLPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnQLPhongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnQLPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnQLPhongMouseExited(evt);
            }
        });

        jLabel64.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Quản lý phòng");

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-room-60 (1).png"))); // NOI18N

        javax.swing.GroupLayout mnQLPhongLayout = new javax.swing.GroupLayout(mnQLPhong);
        mnQLPhong.setLayout(mnQLPhongLayout);
        mnQLPhongLayout.setHorizontalGroup(
            mnQLPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnQLPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel65)
                .addGap(40, 40, 40)
                .addComponent(jLabel64, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        mnQLPhongLayout.setVerticalGroup(
            mnQLPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnQLPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnQLPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel65, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabel64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mnHoaDon.setBackground(new java.awt.Color(20, 38, 66));
        mnHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnHoaDon.setPreferredSize(new java.awt.Dimension(268, 55));
        mnHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnHoaDonMouseExited(evt);
            }
        });

        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Hóa đơn");

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-invoice-60 (1).png"))); // NOI18N

        javax.swing.GroupLayout mnHoaDonLayout = new javax.swing.GroupLayout(mnHoaDon);
        mnHoaDon.setLayout(mnHoaDonLayout);
        mnHoaDonLayout.setHorizontalGroup(
            mnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel67)
                .addGap(40, 40, 40)
                .addComponent(jLabel66, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        mnHoaDonLayout.setVerticalGroup(
            mnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mnVoucher.setBackground(new java.awt.Color(20, 38, 66));
        mnVoucher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnVoucher.setPreferredSize(new java.awt.Dimension(268, 55));
        mnVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnVoucherMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnVoucherMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnVoucherMouseExited(evt);
            }
        });

        jLabel68.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Voucher");

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-voucher-60.png"))); // NOI18N

        javax.swing.GroupLayout mnVoucherLayout = new javax.swing.GroupLayout(mnVoucher);
        mnVoucher.setLayout(mnVoucherLayout);
        mnVoucherLayout.setHorizontalGroup(
            mnVoucherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnVoucherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel69)
                .addGap(40, 40, 40)
                .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        mnVoucherLayout.setVerticalGroup(
            mnVoucherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnVoucherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnVoucherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel69, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mnThongke.setBackground(new java.awt.Color(20, 38, 66));
        mnThongke.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnThongke.setPreferredSize(new java.awt.Dimension(268, 55));
        mnThongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnThongkeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnThongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnThongkeMouseExited(evt);
            }
        });

        jLabel70.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Thống kê");

        jLabel71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-analytics-60.png"))); // NOI18N

        javax.swing.GroupLayout mnThongkeLayout = new javax.swing.GroupLayout(mnThongke);
        mnThongke.setLayout(mnThongkeLayout);
        mnThongkeLayout.setHorizontalGroup(
            mnThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnThongkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel71)
                .addGap(40, 40, 40)
                .addComponent(jLabel70, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        mnThongkeLayout.setVerticalGroup(
            mnThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnThongkeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel71, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabel70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mnCaNhan.setBackground(new java.awt.Color(20, 38, 66));
        mnCaNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnCaNhan.setPreferredSize(new java.awt.Dimension(268, 55));
        mnCaNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnCaNhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnCaNhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnCaNhanMouseExited(evt);
            }
        });

        jLabel72.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Thông tin cá nhân");

        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-user-70.png"))); // NOI18N

        javax.swing.GroupLayout mnCaNhanLayout = new javax.swing.GroupLayout(mnCaNhan);
        mnCaNhan.setLayout(mnCaNhanLayout);
        mnCaNhanLayout.setHorizontalGroup(
            mnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnCaNhanLayout.createSequentialGroup()
                .addComponent(jLabel73)
                .addGap(37, 37, 37)
                .addComponent(jLabel72, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );
        mnCaNhanLayout.setVerticalGroup(
            mnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnCaNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mnDangXuat.setBackground(new java.awt.Color(20, 38, 66));
        mnDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnDangXuat.setPreferredSize(new java.awt.Dimension(268, 55));
        mnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnDangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnDangXuatMouseExited(evt);
            }
        });

        jLabel74.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Đăng xuất");

        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-logout-60 (1).png"))); // NOI18N

        javax.swing.GroupLayout mnDangXuatLayout = new javax.swing.GroupLayout(mnDangXuat);
        mnDangXuat.setLayout(mnDangXuatLayout);
        mnDangXuatLayout.setHorizontalGroup(
            mnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnDangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel75)
                .addGap(40, 40, 40)
                .addComponent(jLabel74, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        mnDangXuatLayout.setVerticalGroup(
            mnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnDangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel75, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jLabel74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnLeftLayout = new javax.swing.GroupLayout(pnLeft);
        pnLeft.setLayout(pnLeftLayout);
        pnLeftLayout.setHorizontalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mnQLKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnQLPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnQLPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnQLSuatChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnQLSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnQLNhanSu, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnThongke, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnLeftLayout.setVerticalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mnQLPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mnQLSuatChieu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mnQLSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mnQLNhanSu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mnQLKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mnQLPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mnVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mnThongke, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mnCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnLeft, java.awt.BorderLayout.WEST);

        pnRight.setLayout(new java.awt.BorderLayout());

        pnTop.setBackground(new java.awt.Color(20, 38, 66));
        pnTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-user-50.png"))); // NOI18N
        pnTop.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, -1, 100));

        txtStaff.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        txtStaff.setForeground(new java.awt.Color(255, 255, 255));
        txtStaff.setText("txtStaff");
        pnTop.add(txtStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, -1, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-menu-vertical-26.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnTop.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 6, -1, 90));

        pnRight.add(pnTop, java.awt.BorderLayout.NORTH);

        pnContent.setBackground(new java.awt.Color(255, 255, 255));
        pnContent.setLayout(new java.awt.BorderLayout());
        pnRight.add(pnContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnRight, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void menuSwitch(JPanel panelChuyen, TabMenu tabMoi, JPanel panelTab) {
//        Component oldCom;
        if (currentTab == tabMoi) {
            return;
        }
        mnCaNhan.setBackground(new Color(20, 38, 66));
        mnDangXuat.setBackground(new Color(20, 38, 66));
        mnHoaDon.setBackground(new Color(20, 38, 66));
        mnQLKhachHang.setBackground(new Color(20, 38, 66));
        mnQLNhanSu.setBackground(new Color(20, 38, 66));
        mnQLPhim.setBackground(new Color(20, 38, 66));
        mnQLPhong.setBackground(new Color(20, 38, 66));
        mnQLSanPham.setBackground(new Color(20, 38, 66));
        mnQLSuatChieu.setBackground(new Color(20, 38, 66));
        mnThongke.setBackground(new Color(20, 38, 66));
        mnVoucher.setBackground(new Color(20, 38, 66));

        panelTab.setBackground(new Color(11, 77, 163));
        currentTab = tabMoi;
        pnContent.removeAll();
        pnContent.add(panelChuyen, BorderLayout.CENTER);
        pnContent.revalidate();
        pnContent.repaint();
    }


    private void mnQLPhimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnQLPhimMouseEntered
        // TODO add your handling code here:
        mnQLPhim.setBackground(new Color(11, 77, 163));
    }//GEN-LAST:event_mnQLPhimMouseEntered

    private void mnQLPhimMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnQLPhimMouseExited
        // TODO add your handling code here:
        if (!currentTab.equals(TabMenu.TAB_PHIM))
            mnQLPhim.setBackground(new Color(20, 38, 66));
    }//GEN-LAST:event_mnQLPhimMouseExited

    private void mnQLSuatChieuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnQLSuatChieuMouseEntered
        // TODO add your handling code here:
        mnQLSuatChieu.setBackground(new Color(11, 77, 163));
    }//GEN-LAST:event_mnQLSuatChieuMouseEntered

    private void mnQLSuatChieuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnQLSuatChieuMouseExited
        // TODO add your handling code here:
        if (!currentTab.equals(TabMenu.TAB_SUATCHIEU))
            mnQLSuatChieu.setBackground(new Color(20, 38, 66));
    }//GEN-LAST:event_mnQLSuatChieuMouseExited

    private void mnQLNhanSuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnQLNhanSuMouseEntered
        // TODO add your handling code here:
        mnQLNhanSu.setBackground(new Color(11, 77, 163));
    }//GEN-LAST:event_mnQLNhanSuMouseEntered

    private void mnQLNhanSuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnQLNhanSuMouseExited
        // TODO add your handling code here:
        if (!currentTab.equals(TabMenu.TAB_NHANSU))
            mnQLNhanSu.setBackground(new Color(20, 38, 66));
    }//GEN-LAST:event_mnQLNhanSuMouseExited

    private void mnQLSanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnQLSanPhamMouseEntered
        // TODO add your handling code here:
        mnQLSanPham.setBackground(new Color(11, 77, 163));
    }//GEN-LAST:event_mnQLSanPhamMouseEntered

    private void mnQLSanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnQLSanPhamMouseExited
        // TODO add your handling code here:
        if (!currentTab.equals(TabMenu.TAB_SANPHAM))
            mnQLSanPham.setBackground(new Color(20, 38, 66));
    }//GEN-LAST:event_mnQLSanPhamMouseExited

    private void mnQLKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnQLKhachHangMouseEntered
        // TODO add your handling code here:
        mnQLKhachHang.setBackground(new Color(11, 77, 163));
    }//GEN-LAST:event_mnQLKhachHangMouseEntered

    private void mnQLKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnQLKhachHangMouseExited
        // TODO add your handling code here:
        if (!currentTab.equals(TabMenu.TAB_KHACHANG))
            mnQLKhachHang.setBackground(new Color(20, 38, 66));
    }//GEN-LAST:event_mnQLKhachHangMouseExited

    private void mnQLPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnQLPhongMouseEntered
        // TODO add your handling code here:
        mnQLPhong.setBackground(new Color(11, 77, 163));
    }//GEN-LAST:event_mnQLPhongMouseEntered

    private void mnQLPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnQLPhongMouseExited
        // TODO add your handling code here:
        if (!currentTab.equals(TabMenu.TAB_PHONG))
            mnQLPhong.setBackground(new Color(20, 38, 66));
    }//GEN-LAST:event_mnQLPhongMouseExited

    private void mnVoucherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnVoucherMouseEntered
        // TODO add your handling code here:
        mnVoucher.setBackground(new Color(11, 77, 163));
    }//GEN-LAST:event_mnVoucherMouseEntered

    private void mnVoucherMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnVoucherMouseExited
        // TODO add your handling code here:
        if (!currentTab.equals(TabMenu.TAB_VOUCHER))
            mnVoucher.setBackground(new Color(20, 38, 66));
    }//GEN-LAST:event_mnVoucherMouseExited

    private void mnThongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnThongkeMouseEntered
        // TODO add your handling code here:
        mnThongke.setBackground(new Color(11, 77, 163));
    }//GEN-LAST:event_mnThongkeMouseEntered

    private void mnThongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnThongkeMouseExited
        // TODO add your handling code here:
        if (!currentTab.equals(TabMenu.TAB_THONGKE))
            mnThongke.setBackground(new Color(20, 38, 66));
    }//GEN-LAST:event_mnThongkeMouseExited

    private void mnCaNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnCaNhanMouseEntered
        // TODO add your handling code here:
        mnCaNhan.setBackground(new Color(11, 77, 163));
    }//GEN-LAST:event_mnCaNhanMouseEntered

    private void mnCaNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnCaNhanMouseExited
        // TODO add your handling code here:

        if (!currentTab.equals(TabMenu.TAB_CANHAN_QL))
            mnCaNhan.setBackground(new Color(20, 38, 66));
    }//GEN-LAST:event_mnCaNhanMouseExited

    private void mnDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDangXuatMouseEntered
        // TODO add your handling code here:
        mnDangXuat.setBackground(new Color(11, 77, 163));
    }//GEN-LAST:event_mnDangXuatMouseEntered

    private void mnDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDangXuatMouseExited
        // TODO add your handling code here:
        mnDangXuat.setBackground(new Color(20, 38, 66));
    }//GEN-LAST:event_mnDangXuatMouseExited

    private void pnLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLeftMouseClicked
        // TODO add your handling code here:  
    }//GEN-LAST:event_pnLeftMouseClicked

    private void mnQLPhimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnQLPhimMouseClicked
        // TODO add your handling code here:
        menuSwitch(tabPhim, TabMenu.TAB_PHIM, mnQLPhim);
    }//GEN-LAST:event_mnQLPhimMouseClicked

    private void mnQLSuatChieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnQLSuatChieuMouseClicked
        // TODO add your handling code here:
        tabSuatChieu = new TAB_SuatChieu();
        menuSwitch(tabSuatChieu, TabMenu.TAB_SUATCHIEU, mnQLSuatChieu);
    }//GEN-LAST:event_mnQLSuatChieuMouseClicked

    private void mnQLSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnQLSanPhamMouseClicked
        // TODO add your handling code here:
        menuSwitch(tabSanPham, TabMenu.TAB_SANPHAM, mnQLSanPham);
    }//GEN-LAST:event_mnQLSanPhamMouseClicked

    private void mnQLNhanSuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnQLNhanSuMouseClicked
        // TODO add your handling code here:
        menuSwitch(tabNhanSu, TabMenu.TAB_NHANSU, mnQLNhanSu);
    }//GEN-LAST:event_mnQLNhanSuMouseClicked

    private void mnQLKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnQLKhachHangMouseClicked
        // TODO add your handling code here:
        menuSwitch(tabKhachHang, TabMenu.TAB_KHACHANG, mnQLKhachHang);
    }//GEN-LAST:event_mnQLKhachHangMouseClicked

    private void mnQLPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnQLPhongMouseClicked
        // TODO add your handling code here:
        menuSwitch(tabPhong, TabMenu.TAB_PHONG, mnQLPhong);
    }//GEN-LAST:event_mnQLPhongMouseClicked

    private void mnHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnHoaDonMouseClicked
        // TODO add your handling code here:
        menuSwitch(tabHoaDon, TabMenu.TAB_HOADON, mnHoaDon);
    }//GEN-LAST:event_mnHoaDonMouseClicked

    private void mnVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnVoucherMouseClicked
        // TODO add your handling code here:
        menuSwitch(tabVoucher, TabMenu.TAB_VOUCHER, mnVoucher);
    }//GEN-LAST:event_mnVoucherMouseClicked

    private void mnThongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnThongkeMouseClicked
        // TODO add your handling code here:
        menuSwitch(tabThongKe, TabMenu.TAB_THONGKE, mnThongke);
    }//GEN-LAST:event_mnThongkeMouseClicked

    private void mnCaNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnCaNhanMouseClicked
        // TODO add your handling code here:
        menuSwitch(tabCaNhan, TabMenu.TAB_CANHAN_QL, mnCaNhan);
    }//GEN-LAST:event_mnCaNhanMouseClicked

    private void mnDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnDangXuatMouseClicked
        // TODO add your handling code here:
        CurrentStaff.setStaff(null);
        this.setVisible(false);
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_mnDangXuatMouseClicked

    private void mnHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnHoaDonMouseExited
        // TODO add your handling code here:
        if (!currentTab.equals(TabMenu.TAB_HOADON))
            mnHoaDon.setBackground(new Color(20, 38, 66));
    }//GEN-LAST:event_mnHoaDonMouseExited

    private void mnHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnHoaDonMouseEntered
        // TODO add your handling code here:
        mnHoaDon.setBackground(new Color(11, 77, 163));
    }//GEN-LAST:event_mnHoaDonMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuManager_QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuManager_QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuManager_QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuManager_QL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuManager_QL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JPanel logo;
    private javax.swing.JPanel mnCaNhan;
    private javax.swing.JPanel mnDangXuat;
    private javax.swing.JPanel mnHoaDon;
    private javax.swing.JPanel mnQLKhachHang;
    private javax.swing.JPanel mnQLNhanSu;
    private javax.swing.JPanel mnQLPhim;
    private javax.swing.JPanel mnQLPhong;
    private javax.swing.JPanel mnQLSanPham;
    private javax.swing.JPanel mnQLSuatChieu;
    private javax.swing.JPanel mnThongke;
    private javax.swing.JPanel mnVoucher;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnRight;
    private javax.swing.JPanel pnTop;
    private javax.swing.JLabel txtStaff;
    // End of variables declaration//GEN-END:variables
}
