/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.manager;

/**
 *
 * @author Hoang
 */
import gui.custom.CustomComboBoxUI;
import gui.custom.CustomScrollBarUI;
import bus.MovieBUS;
import bus.MovieTypeBUS;
import connectDB.ConnectDB;
import entity.Movie;
import javax.swing.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;
import entity.Movie;
import entity.MovieType;
import enums.MovieStatus;
import gui.custom.TableActionCellEditorOnlyEdit;
import gui.custom.TableActionCellRenderOnlyEdit;
import gui.custom.TableActionEventOnlyEdit;
import java.awt.image.BufferedImage;
import java.util.*;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import util.FileManager;

public class TAB_Phim extends javax.swing.JPanel {

    private MovieBUS movieBUS;
    private MovieTypeBUS movieTypeBUS;
    private FileManager fileManager;
    private javax.swing.table.DefaultTableModel modelTable;
    private File selectedFile;
    private File selectedFileSua;

    /**
     * Creates new form TAB_Phim
     */
    public TAB_Phim() {
        movieBUS = new MovieBUS();
        movieTypeBUS = new MovieTypeBUS();
        fileManager = new FileManager();
        initComponents();

        TableActionEventOnlyEdit event = (int row) -> {
            int selectedRow = bangPhim.getSelectedRow();
            Movie movie = movieBUS.getMovieById(bangPhim.getValueAt(selectedRow, 0).toString());
            modalSuaPhim.setLocationRelativeTo(null);
            jcbTheLoaiXem.removeAllItems();
            for (MovieType mvt : movieTypeBUS.getAllMovieType()) {
                jcbTheLoaiXem.addItem(mvt.getName());
            }
            fillTableView(movie);
            modalSuaPhim.setVisible(true);
            bangPhim.getCellEditor().stopCellEditing();
        };

        bangPhim.getColumnModel().getColumn(7).setCellRenderer(new TableActionCellRenderOnlyEdit());
        bangPhim.getColumnModel().getColumn(7).setCellEditor(new TableActionCellEditorOnlyEdit(event));
        for (MovieType mvt : movieTypeBUS.getAllMovieType()) {
            jcbTheLoai.addItem(mvt.getName());
        }
        loadData("", MovieStatus.PLAYING);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modalThemPhim = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        lbNam = new javax.swing.JLabel();
        txtThoiLuongThem = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        txtTenPhimThem = new javax.swing.JTextField();
        txtTacGiaThem = new javax.swing.JTextField();
        txtNamThem = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txtQuocGiaThem = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        boxHinh = new javax.swing.JPanel();
        lbHinhThem = new javax.swing.JLabel();
        btnChonHinh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbNam3 = new javax.swing.JLabel();
        txtNgonNguThem = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jcbTheLoai = new javax.swing.JComboBox<>();
        modalSuaPhim = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        lbNam1 = new javax.swing.JLabel();
        txtThoiLuongXem = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtMoTaXem = new javax.swing.JTextArea();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        txtTenPhimXem = new javax.swing.JTextField();
        txtTacGiaXem = new javax.swing.JTextField();
        txtNamXem = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        txtQuocGiaXem = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        btnSuaphim = new javax.swing.JButton();
        boxHinh1 = new javax.swing.JPanel();
        lbHinhXem = new javax.swing.JLabel();
        btnSuaHinh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbNam2 = new javax.swing.JLabel();
        trangThaiXem = new javax.swing.JComboBox<>();
        txtNgonNguXem = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jcbTheLoaiXem = new javax.swing.JComboBox<>();
        pnRight = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bangPhim = new javax.swing.JTable();
        btnThemPhim = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jcbTT = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblKetqua = new javax.swing.JLabel();

        modalThemPhim.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        modalThemPhim.setTitle("Them phim");
        modalThemPhim.setBackground(new java.awt.Color(255, 255, 255));
        modalThemPhim.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modalThemPhim.setModal(true);
        modalThemPhim.setResizable(false);
        modalThemPhim.setSize(new java.awt.Dimension(980, 680));
        modalThemPhim.setType(java.awt.Window.Type.POPUP);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        lbNam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNam.setText("Năm phát hành");

        txtThoiLuongThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtThoiLuongThem.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        txtThoiLuongThem.setMargin(new java.awt.Insets(2, 0, 2, 0));
        txtThoiLuongThem.setPreferredSize(new java.awt.Dimension(200, 50));
        txtThoiLuongThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThoiLuongThemActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel43.setText("Thời lượng ( phút)");

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel44.setText("Quốc gia");

        txtMoTa.setColumns(20);
        txtMoTa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMoTa.setLineWrap(true);
        txtMoTa.setRows(5);
        txtMoTa.setWrapStyleWord(true);
        txtMoTa.setBorder(javax.swing.BorderFactory.createLineBorder(Color.LIGHT_GRAY));
        jScrollPane4.setViewportView(txtMoTa);

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel46.setText("Tên phim");

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel47.setText("Thể loại");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
        );

        txtTenPhimThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenPhimThem.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        txtTenPhimThem.setMargin(new java.awt.Insets(2, 0, 2, 0));
        txtTenPhimThem.setPreferredSize(new java.awt.Dimension(200, 50));
        txtTenPhimThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenPhimThemActionPerformed(evt);
            }
        });

        txtTacGiaThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTacGiaThem.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        txtTacGiaThem.setMargin(new java.awt.Insets(2, 0, 2, 0));
        txtTacGiaThem.setPreferredSize(new java.awt.Dimension(200, 50));
        txtTacGiaThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTacGiaThemActionPerformed(evt);
            }
        });

        txtNamThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNamThem.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        txtNamThem.setMargin(new java.awt.Insets(2, 0, 2, 0));
        txtNamThem.setPreferredSize(new java.awt.Dimension(200, 50));
        txtNamThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamThemActionPerformed(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel49.setText("Tác giả");

        txtQuocGiaThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtQuocGiaThem.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        txtQuocGiaThem.setMargin(new java.awt.Insets(2, 0, 2, 0));
        txtQuocGiaThem.setPreferredSize(new java.awt.Dimension(200, 50));
        txtQuocGiaThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuocGiaThemActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(11, 77, 163));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Thêm phim");
        btnSubmit.setBorder(null);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        boxHinh.setPreferredSize(new java.awt.Dimension(210, 300));

        lbHinhThem.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbHinhThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHinhThem.setText("Thêm ảnh");

        javax.swing.GroupLayout boxHinhLayout = new javax.swing.GroupLayout(boxHinh);
        boxHinh.setLayout(boxHinhLayout);
        boxHinhLayout.setHorizontalGroup(
            boxHinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbHinhThem, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        boxHinhLayout.setVerticalGroup(
            boxHinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbHinhThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnChonHinh.setBackground(new java.awt.Color(11, 77, 163));
        btnChonHinh.setToolTipText("");
        btnChonHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonHinhActionPerformed(evt);
            }
        });

        jLabel1.setText("210 x 300");

        lbNam3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNam3.setText("Mô tả");

        txtNgonNguThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNgonNguThem.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        txtNgonNguThem.setMargin(new java.awt.Insets(2, 0, 2, 0));
        txtNgonNguThem.setPreferredSize(new java.awt.Dimension(200, 50));
        txtNgonNguThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgonNguThemActionPerformed(evt);
            }
        });

        jLabel68.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel68.setText("Ngôn ngữ");

        jcbTheLoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbTheLoai.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        jcbTheLoai.setMaximumRowCount(4);
        jcbTheLoai.setUI(new CustomComboBoxUI());

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel46)
                            .addComponent(txtTenPhimThem, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNam3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTacGiaThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel49))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel68)
                                    .addComponent(txtNgonNguThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel44)
                            .addComponent(txtQuocGiaThem, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(jLabel47)
                            .addComponent(jcbTheLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(boxHinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChonHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtThoiLuongThem, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNam)
                                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 36, Short.MAX_VALUE))
                            .addComponent(txtNamThem, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addGap(29, 29, 29))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(txtTenPhimThem, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtThoiLuongThem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jcbTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel44)
                        .addComponent(jLabel68)
                        .addComponent(lbNam)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtQuocGiaThem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(txtNamThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTacGiaThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNgonNguThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbNam3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boxHinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4)))
                    .addComponent(btnChonHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jScrollPane4.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        jScrollPane4.getHorizontalScrollBar().setUI(new CustomScrollBarUI());

        javax.swing.GroupLayout modalThemPhimLayout = new javax.swing.GroupLayout(modalThemPhim.getContentPane());
        modalThemPhim.getContentPane().setLayout(modalThemPhimLayout);
        modalThemPhimLayout.setHorizontalGroup(
            modalThemPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        modalThemPhimLayout.setVerticalGroup(
            modalThemPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        modalSuaPhim.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        modalSuaPhim.setTitle("Chi tiết phim");
        modalSuaPhim.setBackground(new java.awt.Color(255, 255, 255));
        modalSuaPhim.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modalSuaPhim.setModal(true);
        modalSuaPhim.setResizable(false);
        modalSuaPhim.setSize(new java.awt.Dimension(980, 680));
        modalSuaPhim.setType(java.awt.Window.Type.POPUP);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        lbNam1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNam1.setText("Năm");

        txtThoiLuongXem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtThoiLuongXem.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        txtThoiLuongXem.setMargin(new java.awt.Insets(2, 0, 2, 0));
        txtThoiLuongXem.setPreferredSize(new java.awt.Dimension(200, 50));
        txtThoiLuongXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThoiLuongXemActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel45.setText("Thời lượng ( phút)");

        jLabel60.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel60.setText("Quốc gia");

        jScrollPane5.setBorder(null);
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtMoTaXem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMoTaXem.setLineWrap(true);
        txtMoTaXem.setRows(5);
        txtMoTaXem.setWrapStyleWord(true);
        txtMoTaXem.setBorder(javax.swing.BorderFactory.createLineBorder(Color.LIGHT_GRAY));
        jScrollPane5.setViewportView(txtMoTaXem);

        jLabel61.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel61.setText("Tên phim");

        jLabel62.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel62.setText("Thể loại");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel63, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
        );

        txtTenPhimXem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenPhimXem.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        txtTenPhimXem.setMargin(new java.awt.Insets(2, 0, 2, 0));
        txtTenPhimXem.setPreferredSize(new java.awt.Dimension(200, 50));
        txtTenPhimXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenPhimXemActionPerformed(evt);
            }
        });

        txtTacGiaXem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTacGiaXem.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        txtTacGiaXem.setMargin(new java.awt.Insets(2, 0, 2, 0));
        txtTacGiaXem.setPreferredSize(new java.awt.Dimension(200, 50));
        txtTacGiaXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTacGiaXemActionPerformed(evt);
            }
        });

        txtNamXem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNamXem.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        txtNamXem.setMargin(new java.awt.Insets(2, 0, 2, 0));
        txtNamXem.setPreferredSize(new java.awt.Dimension(200, 50));
        txtNamXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamXemActionPerformed(evt);
            }
        });

        jLabel64.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel64.setText("Tác giả");

        txtQuocGiaXem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtQuocGiaXem.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        txtQuocGiaXem.setMargin(new java.awt.Insets(2, 0, 2, 0));
        txtQuocGiaXem.setPreferredSize(new java.awt.Dimension(200, 50));
        txtQuocGiaXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuocGiaXemActionPerformed(evt);
            }
        });

        jLabel65.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel65.setText("Trạng thái");

        btnSuaphim.setBackground(new java.awt.Color(11, 77, 163));
        btnSuaphim.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSuaphim.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaphim.setText("Xác nhận");
        btnSuaphim.setBorder(null);
        btnSuaphim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaphimActionPerformed(evt);
            }
        });

        boxHinh1.setPreferredSize(new java.awt.Dimension(210, 300));

        javax.swing.GroupLayout boxHinh1Layout = new javax.swing.GroupLayout(boxHinh1);
        boxHinh1.setLayout(boxHinh1Layout);
        boxHinh1Layout.setHorizontalGroup(
            boxHinh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbHinhXem, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        boxHinh1Layout.setVerticalGroup(
            boxHinh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbHinhXem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnSuaHinh.setBackground(new java.awt.Color(11, 77, 163));
        btnSuaHinh.setToolTipText("");
        btnSuaHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaHinhActionPerformed(evt);
            }
        });

        jLabel2.setText("210 x 300");

        lbNam2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNam2.setText("Mô tả");

        trangThaiXem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        trangThaiXem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang phát hành", "Ngưng phát hành" }));
        trangThaiXem.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        trangThaiXem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trangThaiXem.setUI(new CustomComboBoxUI());

        txtNgonNguXem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNgonNguXem.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        txtNgonNguXem.setMargin(new java.awt.Insets(2, 0, 2, 0));
        txtNgonNguXem.setPreferredSize(new java.awt.Dimension(200, 50));
        txtNgonNguXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgonNguXemActionPerformed(evt);
            }
        });

        jLabel69.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel69.setText("Ngôn ngữ");

        jcbTheLoaiXem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbTheLoaiXem.setUI(new CustomComboBoxUI());
        jcbTheLoaiXem.setMaximumRowCount(4);
        jcbTheLoaiXem.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        jcbTheLoaiXem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcbTheLoaiXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTheLoaiXemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel61)
                            .addComponent(txtTenPhimXem, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTacGiaXem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel64))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel69)
                                    .addComponent(txtNgonNguXem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel60)
                            .addComponent(txtQuocGiaXem, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(jLabel62)
                            .addComponent(jcbTheLoaiXem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(boxHinh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSuaHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbNam2))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSuaphim, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trangThaiXem, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(txtThoiLuongXem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtNamXem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel65)
                                    .addComponent(lbNam1))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(19, 19, 19))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(jLabel62)
                    .addComponent(jLabel65))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(trangThaiXem, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(txtTenPhimXem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jcbTheLoaiXem, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel60)
                        .addComponent(jLabel45)
                        .addComponent(jLabel69)))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtQuocGiaXem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTacGiaXem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNgonNguXem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtThoiLuongXem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNam1)
                            .addComponent(lbNam2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boxHinh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamXem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSuaphim, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
                    .addComponent(btnSuaHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(37, 37, 37))
        );

        jScrollPane5.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        jScrollPane5.getHorizontalScrollBar().setUI(new CustomScrollBarUI());

        javax.swing.GroupLayout modalSuaPhimLayout = new javax.swing.GroupLayout(modalSuaPhim.getContentPane());
        modalSuaPhim.getContentPane().setLayout(modalSuaPhimLayout);
        modalSuaPhimLayout.setHorizontalGroup(
            modalSuaPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        modalSuaPhimLayout.setVerticalGroup(
            modalSuaPhimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setMinimumSize(new java.awt.Dimension(1083, 765));
        pnRight.setPreferredSize(new java.awt.Dimension(1083, 765));
        pnRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        String[] header = {"Mã phim","Tên phim", "Tác giả","Thể loại", "Quốc gia", "Thời lượng", "Trạng thái", "Thao tác"};
        modelTable = new DefaultTableModel(header,0){
            boolean[] canEdit = new boolean [] {
                false,false, false, false,false, false, false, true
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        bangPhim.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        bangPhim.setModel(modelTable);
        bangPhim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bangPhim.setGridColor(new java.awt.Color(255, 255, 255));
        bangPhim.setRowHeight(50);
        bangPhim.setSelectionBackground(new java.awt.Color(54,107,177));
        bangPhim.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        bangPhim.getTableHeader().setReorderingAllowed(false);
        bangPhim.getTableHeader().setPreferredSize(new Dimension(bangPhim.getColumnModel().getTotalColumnWidth(), 50));
        bangPhim.getTableHeader().setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        bangPhim.getTableHeader().setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                label.addMouseListener(null);

                return label;
            }
        });
        bangPhim.getTableHeader().setFont(new Font("Segoe UI", 0 , 16));
        jScrollPane2.setViewportView(bangPhim);
        TableColumnModel columnModel = bangPhim.getColumnModel();
        TableColumn idColl = columnModel.getColumn(0);
        TableColumn tenPhimColl = columnModel.getColumn(1);
        TableColumn tacGiaColl = columnModel.getColumn(2);
        TableColumn quocGiaColl = columnModel.getColumn(3);
        TableColumn thoiLuongColl = columnModel.getColumn(4);
        TableColumn namColl = columnModel.getColumn(5);
        TableColumn trangThaiColl = columnModel.getColumn(6);
        TableColumn thaoTacColl = columnModel.getColumn(7);

        idColl.setPreferredWidth(50);
        tenPhimColl.setPreferredWidth(200);
        tacGiaColl.setPreferredWidth(120);
        quocGiaColl.setPreferredWidth(100);
        thoiLuongColl.setPreferredWidth(70);
        namColl.setPreferredWidth(60);
        trangThaiColl.setPreferredWidth(120);
        thaoTacColl.setPreferredWidth(50);

        bangPhim.getTableHeader().setResizingAllowed(false);
        for (int i = 0; i < bangPhim.getColumnCount(); i++) {
            bangPhim.getColumnModel().getColumn(i).setResizable(false);
        }

        pnRight.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1540, 750));
        jScrollPane2.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        jScrollPane2.getHorizontalScrollBar().setUI(new CustomScrollBarUI());
        jScrollPane2.getViewport().setBackground(Color.WHITE);

        btnThemPhim.setBackground(new java.awt.Color(11, 77, 163));
        btnThemPhim.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnThemPhim.setForeground(new java.awt.Color(255, 255, 255));
        btnThemPhim.setText("Thêm phim");
        btnThemPhim.setBorder(null);
        btnThemPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPhimActionPerformed(evt);
            }
        });
        pnRight.add(btnThemPhim, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 30, 130, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        pnRight.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 30, 40));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtSearch.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        pnRight.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 310, 40));

        jcbTT.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jcbTT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang phát hành", "Ngưng phát hành" }));
        jcbTT.setUI(new CustomComboBoxUI());
        jcbTT.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        jcbTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTTActionPerformed(evt);
            }
        });
        pnRight.add(jcbTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 230, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Kết quả:");
        pnRight.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 850, -1, -1));

        lblKetqua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKetqua.setText("0");
        pnRight.add(lblKetqua, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 850, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1622, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 1616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 934, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fillTableView(Movie movie) {
        selectedFileSua = null;
        MovieType movieType = movieTypeBUS.getMovieTypeById(movie.getMovieType().getMovieTypeId());
        txtThoiLuongXem.setText(movie.getRunningTime() + "");
        jcbTheLoaiXem.setSelectedItem(movieType.getName());
        txtTenPhimXem.setText(movie.getName());
        txtTacGiaXem.setText(movie.getAuthor());
        txtNamXem.setText(movie.getReleaseYear() + "");
        txtQuocGiaXem.setText(movie.getCountry());
        txtNgonNguXem.setText(movie.getLanguage());
        txtMoTaXem.setText(movie.getDescription());
        if (movie.getMovieStatus().equals(MovieStatus.PLAYING)) {
            trangThaiXem.setSelectedIndex(0);
        } else {
            trangThaiXem.setSelectedIndex(1);
        }

        String imagePath = "/img/" + movie.getPoster();
        try {
            BufferedImage originalImage = ImageIO.read(getClass().getResource(imagePath));
            // Resize ảnh
            Image resizedImage = originalImage.getScaledInstance(210, 300, Image.SCALE_SMOOTH);
            // Tạo ImageIcon từ ảnh đã resize
            ImageIcon imageIcon = new ImageIcon(resizedImage);
            // Set ImageIcon cho JLabel
            lbHinhXem.setIcon(imageIcon);
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    private boolean checkValid(JTextField txtTenPhimXem, JTextField txtThoiLuongXem, JTextField txtTacGiaXem,
            JTextField txtNgonNguXem, JTextField txtQuocGiaXem, JTextField txtNamXem, boolean update) {
        String tenPhim = txtTenPhimXem.getText();
        String thoiLuong = txtThoiLuongXem.getText();
        String tacGia = txtTacGiaXem.getText();
        String ngonNgu = txtNgonNguXem.getText();
        String quocGia = txtQuocGiaXem.getText();
        String nam = txtNamXem.getText().trim();

        if (tenPhim.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Tên phim không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (thoiLuong.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Thời lượng phim không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            try {
                int thoiLuong_parse = Integer.parseInt(thoiLuong);
                if (thoiLuong_parse <= 0) {
                    JOptionPane.showMessageDialog(null, "Thời lượng phim phải lớn hơn 0", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Thời lượng phim phải là số", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        if (tacGia.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Tác giả không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (ngonNgu.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Ngôn ngữ không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (quocGia.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Quốc gia không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (nam.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Năm phát hành không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            try {
                int nam_parse = Integer.parseInt(nam);
                if (nam_parse <= 1900) {
                    JOptionPane.showMessageDialog(null, "Năm phát hành phải lớn hơn 1900", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Năm phát hành phải là số", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        if (update == false && selectedFile == null) {
            JOptionPane.showMessageDialog(null, "Ảnh phim không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void clearData() {
        txtThoiLuongThem.setText("");
        jcbTheLoai.setSelectedIndex(0);
        txtTenPhimThem.setText("");
        txtTacGiaThem.setText("");
        txtNamThem.setText("");
        txtQuocGiaThem.setText("");
        txtNgonNguThem.setText("");
        txtMoTa.setText("");
        selectedFile = null;
        lbHinhThem.setIcon(null);
    }

    private void loadData(String keyword, MovieStatus movieStatus) {
        modelTable.setRowCount(0);
        java.util.List<Movie> movies = movieBUS.getMovieByKeywordAndMovieStatus(keyword, movieStatus);
        for (Movie movie : movies) {
            MovieType movieType = movieTypeBUS.getMovieTypeById(movie.getMovieType().getMovieTypeId());
            modelTable.addRow(new Object[]{movie.getMovieId(), movie.getName(), movie.getAuthor(), movieType.getName(),
                movie.getCountry(), movie.getRunningTime() + " phút", movie.getMovieStatus() == MovieStatus.PLAYING ? "Đang phát hành"
                : "Ngưng phát hành"});
        }
        lblKetqua.setText(movies.size() + "");
    }


    private void btnThemPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPhimActionPerformed
        // TODO add your handling code here:
        modalThemPhim.setLocationRelativeTo(null);
        clearData();
        modalThemPhim.setVisible(true);
    }//GEN-LAST:event_btnThemPhimActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String search = txtSearch.getText();
        MovieStatus movieStatus = jcbTT.getSelectedItem().equals("Đang phát hành") ? MovieStatus.PLAYING : MovieStatus.STOPPED;
        loadData(search, movieStatus);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jcbTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTTActionPerformed
        // TODO add your handling code here:
        String search = txtSearch.getText();
        MovieStatus movieStatus = jcbTT.getSelectedItem().equals("Đang phát hành") ? MovieStatus.PLAYING : MovieStatus.STOPPED;
        loadData(search, movieStatus);
    }//GEN-LAST:event_jcbTTActionPerformed

    private void txtThoiLuongThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThoiLuongThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThoiLuongThemActionPerformed

    private void txtTenPhimThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenPhimThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenPhimThemActionPerformed

    private void txtTacGiaThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTacGiaThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTacGiaThemActionPerformed

    private void txtNamThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamThemActionPerformed

    private void txtQuocGiaThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuocGiaThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuocGiaThemActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        if (checkValid(txtTenPhimThem, txtThoiLuongThem, txtTacGiaThem, txtNgonNguThem, txtQuocGiaThem, txtNamThem, false)) {
            String thoiLuong = txtThoiLuongThem.getText().trim();
            String theLoai = (String) jcbTheLoai.getSelectedItem();
            String tenPhim = txtTenPhimThem.getText().trim();
            String tacGia = txtTacGiaThem.getText().trim();
            String nam = txtNamThem.getText().trim();
            String quocGia = txtQuocGiaThem.getText().trim();
            String ngonNgu = txtNgonNguThem.getText().trim();
            String moTa = txtMoTa.getText().trim();
            if(movieBUS.existsByName(tenPhim)){
                JOptionPane.showMessageDialog(null, "Tên Phim đã tồn tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String image = fileManager.createFile(selectedFile);
            if (image == null) {
                JOptionPane.showMessageDialog(null, "Không phải file ảnh", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Movie movie = new Movie(null, tenPhim, Integer.parseInt(thoiLuong), quocGia, ngonNgu, moTa,
                    Integer.parseInt(nam), tacGia, image, MovieStatus.PLAYING,
                    movieTypeBUS.getMovieTypeByName(theLoai));
            if (movieBUS.insertMovie(movie)) {
                JOptionPane.showMessageDialog(null, "Thêm mới thành công");
                loadData("", MovieStatus.PLAYING);
                modalThemPhim.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Thêm mới thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnChonHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonHinhActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();
            try {
                Image image = ImageIO.read(selectedFile);
                ImageIcon icon = new ImageIcon(image.getScaledInstance(210, 300, Image.SCALE_SMOOTH));
                lbHinhThem.setIcon(icon);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Không phải file ảnh");
            }
        }
    }//GEN-LAST:event_btnChonHinhActionPerformed

    private void txtNgonNguThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgonNguThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgonNguThemActionPerformed

    private void txtThoiLuongXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThoiLuongXemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThoiLuongXemActionPerformed

    private void txtTenPhimXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenPhimXemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenPhimXemActionPerformed

    private void txtTacGiaXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTacGiaXemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTacGiaXemActionPerformed

    private void txtNamXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamXemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamXemActionPerformed

    private void txtQuocGiaXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuocGiaXemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuocGiaXemActionPerformed

    private void btnSuaphimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaphimActionPerformed
        // TODO add your handling code here:
        if (checkValid(txtTenPhimXem, txtThoiLuongXem, txtTacGiaXem, txtNgonNguXem, txtQuocGiaXem, txtNamXem, true)) {
            int selectedRow = bangPhim.getSelectedRow();
            String idPhim = bangPhim.getValueAt(selectedRow, 0).toString();
            String thoiLuong = txtThoiLuongXem.getText();
            String theLoai = (String) jcbTheLoaiXem.getSelectedItem();
            String tenPhim = txtTenPhimXem.getText();
            String tacGia = txtTacGiaXem.getText();
            String nam = txtNamXem.getText();
            String quocGia = txtQuocGiaXem.getText();
            String ngonNgu = txtNgonNguXem.getText();
            String moTa = txtMoTaXem.getText();
            String trangThai = (String) trangThaiXem.getSelectedItem();
            if (trangThai.equals("Ngưng phát hành") && movieBUS.findByExistsShowtime(idPhim)) {
                JOptionPane.showMessageDialog(null, "Phim đang có suất chiếu trong tương lai", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Movie movieOld = movieBUS.getMovieById(idPhim);
            if(!movieOld.getName().equals(tenPhim) && movieBUS.existsByName(tenPhim)){
                JOptionPane.showMessageDialog(null, "Tên Phim đã tồn tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(movieOld.getRunningTime() != Integer.parseInt(thoiLuong) && movieBUS.findByExistsShowtime(idPhim)){
                JOptionPane.showMessageDialog(null, "Không thể sửa thời lượng vì phim đang có suất chiếu trong tương lai", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Movie movieNew;
            if (selectedFileSua == null) { // Không update ảnh
                movieNew = new Movie(idPhim, tenPhim, Integer.parseInt(thoiLuong),
                        quocGia, ngonNgu, moTa, Integer.parseInt(nam), tacGia, movieOld.getPoster(),
                        trangThai.equals("Đang phát hành") ? MovieStatus.PLAYING : MovieStatus.STOPPED, movieTypeBUS.getMovieTypeByName(theLoai));
            } else {
                String image = fileManager.updateFile(selectedFileSua, movieOld.getPoster());
                if (image == null) {
                    JOptionPane.showMessageDialog(null, "Không phải file ảnh", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                movieNew = new Movie(idPhim, tenPhim, Integer.parseInt(thoiLuong),
                        quocGia, ngonNgu, moTa, Integer.parseInt(nam), tacGia, image,
                        trangThai.equals("Đang phát hành") ? MovieStatus.PLAYING : MovieStatus.STOPPED, movieTypeBUS.getMovieTypeByName(theLoai));
            }
            if (movieBUS.updateMovie(movieNew)) {
                JOptionPane.showMessageDialog(null, "Cập nhật thành công");
                jcbTT.setSelectedIndex(0);
                loadData("", MovieStatus.PLAYING);
                modalSuaPhim.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSuaphimActionPerformed

    private void btnSuaHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaHinhActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooserSua = new JFileChooser();
        int result = fileChooserSua.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFileSua = fileChooserSua.getSelectedFile();
            try {
                Image image = ImageIO.read(selectedFileSua);
                ImageIcon icon = new ImageIcon(image.getScaledInstance(210, 300, Image.SCALE_SMOOTH));
                lbHinhXem.setIcon(icon);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Không thể chọn hình", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSuaHinhActionPerformed

    private void txtNgonNguXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgonNguXemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgonNguXemActionPerformed

    private void jcbTheLoaiXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTheLoaiXemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTheLoaiXemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangPhim;
    private javax.swing.JPanel boxHinh;
    private javax.swing.JPanel boxHinh1;
    private javax.swing.JButton btnChonHinh;
    private javax.swing.JButton btnSuaHinh;
    private javax.swing.JButton btnSuaphim;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnThemPhim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JComboBox<String> jcbTT;
    private javax.swing.JComboBox<String> jcbTheLoai;
    private javax.swing.JComboBox<String> jcbTheLoaiXem;
    private javax.swing.JLabel lbHinhThem;
    private javax.swing.JLabel lbHinhXem;
    private javax.swing.JLabel lbNam;
    private javax.swing.JLabel lbNam1;
    private javax.swing.JLabel lbNam2;
    private javax.swing.JLabel lbNam3;
    private javax.swing.JLabel lblKetqua;
    private javax.swing.JDialog modalSuaPhim;
    private javax.swing.JDialog modalThemPhim;
    private javax.swing.JPanel pnRight;
    private javax.swing.JComboBox<String> trangThaiXem;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextArea txtMoTaXem;
    private javax.swing.JTextField txtNamThem;
    private javax.swing.JTextField txtNamXem;
    private javax.swing.JTextField txtNgonNguThem;
    private javax.swing.JTextField txtNgonNguXem;
    private javax.swing.JTextField txtQuocGiaThem;
    private javax.swing.JTextField txtQuocGiaXem;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTacGiaThem;
    private javax.swing.JTextField txtTacGiaXem;
    private javax.swing.JTextField txtTenPhimThem;
    private javax.swing.JTextField txtTenPhimXem;
    private javax.swing.JTextField txtThoiLuongThem;
    private javax.swing.JTextField txtThoiLuongXem;
    // End of variables declaration//GEN-END:variables
}
