/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.manager;

/**
 *
 * @author Hoang
 */
import bus.CategoryBUS;
import bus.ProductBUS;
import connectDB.ConnectDB;
import entity.Category;
import entity.Product;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import util.FileManager;
import gui.custom.*;
import java.awt.image.BufferedImage;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class TAB_SanPham extends javax.swing.JPanel {

    private ProductBUS productBUS;
    private CategoryBUS categoryBUS;
    private DecimalFormat formatter = new DecimalFormat("#,###");
    private File fileThem;
    private File fileSua;
    private FileManager fileManager;
    private String productIdLocal;

    /**
     * Creates new form TAB_SanPham
     */
    public TAB_SanPham() {
        productBUS = new ProductBUS();
        categoryBUS = new CategoryBUS();
        fileManager = new FileManager();
        initComponents();
        loadData("", "Tất cả", true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modalThemSP = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        lblTen = new javax.swing.JLabel();
        lblLoai = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        cbbLoai = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        pnThemAnh = new javax.swing.JPanel();
        lblThemAnh = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        modalSuaSP = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        lblTen1 = new javax.swing.JLabel();
        lblLoai1 = new javax.swing.JLabel();
        lblGia1 = new javax.swing.JLabel();
        txtSoLuong1 = new javax.swing.JTextField();
        txtGia1 = new javax.swing.JTextField();
        cbbLoai1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        pnThemAnh1 = new javax.swing.JPanel();
        lblSuaAnh = new javax.swing.JLabel();
        btnCapNhat = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTenSP1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jcbTT = new javax.swing.JComboBox<>();
        pRight = new javax.swing.JPanel();
        pRight_Top = new javax.swing.JPanel();
        txtTimSP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbbTim = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        cbbTrangThai = new javax.swing.JComboBox<>();
        jScrollPaneSP = new javax.swing.JScrollPane();
        pDSSP = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ketQua = new javax.swing.JLabel();

        modalThemSP.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        modalThemSP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modalThemSP.setModal(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblTen.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTen.setText("Tên");

        lblLoai.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblLoai.setText("Loại");

        lblGia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblGia.setText("Giá tiền");

        txtSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtSoLuong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        txtGia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtGia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaActionPerformed(evt);
            }
        });

        cbbLoai.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cbbLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đồ ăn", "Nước uống" }));
        cbbLoai.setBorder(null);
        cbbLoai.setUI(new CustomComboBoxUI());
        cbbLoai.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("THÊM SẢN PHẨM");

        pnThemAnh.setBackground(new java.awt.Color(255, 255, 255));
        pnThemAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnThemAnh.setMinimumSize(new java.awt.Dimension(200, 150));

        javax.swing.GroupLayout pnThemAnhLayout = new javax.swing.GroupLayout(pnThemAnh);
        pnThemAnh.setLayout(pnThemAnhLayout);
        pnThemAnhLayout.setHorizontalGroup(
            pnThemAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThemAnhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThemAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnThemAnhLayout.setVerticalGroup(
            pnThemAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThemAnhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThemAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnThem.setBackground(new java.awt.Color(19, 87, 157));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(19, 87, 157));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-folder-30.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("200x150");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setText("Số lượng");

        txtTenSP.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtTenSP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(113, 113, 113)
                            .addComponent(jLabel4))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(pnThemAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11)
                            .addComponent(jButton4))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblLoai)
                                .addComponent(jLabel7)
                                .addComponent(lblGia)
                                .addComponent(lblTen))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cbbLoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel6)
                        .addGap(253, 253, 253)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(174, Short.MAX_VALUE)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(52, 52, 52)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblTen)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGia, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(lblGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnThemAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton4)))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(btnThem))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(503, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout modalThemSPLayout = new javax.swing.GroupLayout(modalThemSP.getContentPane());
        modalThemSP.getContentPane().setLayout(modalThemSPLayout);
        modalThemSPLayout.setHorizontalGroup(
            modalThemSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modalThemSPLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        modalThemSPLayout.setVerticalGroup(
            modalThemSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        modalThemSP.setSize(448, 632);
        modalThemSP.setLocationRelativeTo(null);
        modalThemSP.setResizable(false);

        modalSuaSP.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        modalSuaSP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modalSuaSP.setMinimumSize(new java.awt.Dimension(556, 743));
        modalSuaSP.setModal(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(556, 743));
        jPanel3.setPreferredSize(new java.awt.Dimension(556, 743));

        lblTen1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTen1.setText("Tên");

        lblLoai1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblLoai1.setText("Loại");

        lblGia1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblGia1.setText("Giá tiền");

        txtSoLuong1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtSoLuong1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtSoLuong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuong1ActionPerformed(evt);
            }
        });

        txtGia1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtGia1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtGia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGia1ActionPerformed(evt);
            }
        });

        cbbLoai1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cbbLoai1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đồ ăn", "Nước uống" }));
        cbbLoai1.setBorder(null);
        cbbLoai1.setUI(new CustomComboBoxUI());
        cbbLoai1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("SỬA SẢN PHẨM");

        pnThemAnh1.setBackground(new java.awt.Color(255, 255, 255));
        pnThemAnh1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnThemAnh1.setMinimumSize(new java.awt.Dimension(200, 150));

        javax.swing.GroupLayout pnThemAnh1Layout = new javax.swing.GroupLayout(pnThemAnh1);
        pnThemAnh1.setLayout(pnThemAnh1Layout);
        pnThemAnh1Layout.setHorizontalGroup(
            pnThemAnh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThemAnh1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSuaAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnThemAnh1Layout.setVerticalGroup(
            pnThemAnh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThemAnh1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSuaAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCapNhat.setBackground(new java.awt.Color(19, 87, 157));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnThem.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(19, 87, 157));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-folder-30.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("200x150");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setText("Số lượng");

        txtTenSP1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtTenSP1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTenSP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSP1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Trạng thái");

        jcbTT.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jcbTT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang bán", "Ngưng bán" }));
        jcbTT.setUI(new CustomComboBoxUI());
        jcbTT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jcbTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLoai1)
                    .addComponent(jLabel10)
                    .addComponent(lblTen1)
                    .addComponent(lblGia1)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pnThemAnh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jButton5))
                    .addComponent(txtGia1)
                    .addComponent(txtSoLuong1)
                    .addComponent(cbbLoai1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbTT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(175, 175, 175))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(167, Short.MAX_VALUE)
                    .addComponent(txtTenSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(61, 61, 61)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lblTen1)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLoai1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbLoai1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGia1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(lblGia1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnThemAnh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton5)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnCapNhat))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel9)))
                .addGap(31, 31, 31))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(txtTenSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(594, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout modalSuaSPLayout = new javax.swing.GroupLayout(modalSuaSP.getContentPane());
        modalSuaSP.getContentPane().setLayout(modalSuaSPLayout);
        modalSuaSPLayout.setHorizontalGroup(
            modalSuaSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        modalSuaSPLayout.setVerticalGroup(
            modalSuaSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        modalSuaSP.setSize(448, 632);
        modalSuaSP.setLocationRelativeTo(null);
        modalSuaSP.setResizable(false);

        pRight.setBackground(new java.awt.Color(255, 255, 255));
        pRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pRight_Top.setBackground(new java.awt.Color(255, 255, 255));
        pRight_Top.setMinimumSize(new java.awt.Dimension(1460, 102));

        txtTimSP.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtTimSP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTimSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimSPActionPerformed(evt);
            }
        });
        txtTimSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimSPKeyReleased(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N

        cbbTim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbbTim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đồ ăn", "Nước uống" }));
        cbbTim.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cbbTim.setUI(new CustomComboBoxUI());
        cbbTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTimActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cinema-64.png"))); // NOI18N
        jButton3.setText("Thêm sản phẩm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbbTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang bán", "Ngưng bán" }));
        cbbTrangThai.setSelectedItem("Đang bán");
        cbbTrangThai.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cbbTrangThai.setUI(new CustomComboBoxUI());
        cbbTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTrangThaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pRight_TopLayout = new javax.swing.GroupLayout(pRight_Top);
        pRight_Top.setLayout(pRight_TopLayout);
        pRight_TopLayout.setHorizontalGroup(
            pRight_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRight_TopLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtTimSP, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 474, Short.MAX_VALUE)
                .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(cbbTim, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pRight_TopLayout.setVerticalGroup(
            pRight_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRight_TopLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pRight_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(pRight_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbbTim, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTimSP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(16, 16, 16))
        );

        pRight.add(pRight_Top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1563, 125));

        jScrollPaneSP.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneSP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneSP.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPaneSP.getVerticalScrollBar().setUI(new CustomScrollBarUI());

        pDSSP.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pDSSPLayout = new javax.swing.GroupLayout(pDSSP);
        pDSSP.setLayout(pDSSPLayout);
        pDSSPLayout.setHorizontalGroup(
            pDSSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1772, Short.MAX_VALUE)
        );
        pDSSPLayout.setVerticalGroup(
            pDSSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );

        jScrollPaneSP.setViewportView(pDSSP);
        jScrollPaneSP.getViewport().setBackground(Color.WHITE);

        pRight.add(jScrollPaneSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 1546, 720));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setText("Kết quả:");
        pRight.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 963, -1, -1));

        ketQua.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ketQua.setText("0");
        pRight.add(ketQua, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 963, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pRight, javax.swing.GroupLayout.PREFERRED_SIZE, 1600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pRight, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clearData() {
        txtTenSP.setText("");
        txtGia.setText("");
        txtSoLuong.setText("");
        cbbLoai.setSelectedIndex(0);
        fileThem = null;
        lblThemAnh.setIcon(null);
    }

    private boolean checkValid(JTextField txtTenSP, JTextField txtSoLuong, JTextField txtGia, boolean update) {
        String name = txtTenSP.getText();
        String unitInStock = txtSoLuong.getText();
        String price = txtGia.getText();
        if (name.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Tên sản phẩm không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (unitInStock.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Số lượng tồn không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            try {
                int unitInStock_parse = Integer.parseInt(unitInStock);
                if (unitInStock_parse <= 0) {
                    JOptionPane.showMessageDialog(null, "Số lượng tồn phải lớn hơn 0", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Số lượng tồn phải là số", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        if (price.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Giá sản phẩm không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            try {
                double price_parse = Double.parseDouble(price);
                if (price_parse <= 0) {
                    JOptionPane.showMessageDialog(null, "Giá sản phẩm phải lớn hơn 0", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Giá sản phẩm phải là số", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        if (update == false) {
            if (fileThem == null) {
                JOptionPane.showMessageDialog(null, "Ảnh sản phẩm không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }

        return true;
    }

    private ImageIcon scaleIcon(ImageIcon icon, int width, int height) {
        Image image = icon.getImage();
        Image imgScale = image.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        return scaledIcon;
    }

    private void loadData(String txtSearch, String type, boolean status) {
        pDSSP.repaint();
        pDSSP.revalidate();
        pDSSP.removeAll();
        List<Product> products = productBUS.getProductByKeywordAndCategory(txtSearch, type, status);
        ketQua.setText(products.size() + "");
        pDSSP.setLayout(new GridBagLayout());
        GridBagConstraints constraints = new GridBagConstraints();
        constraints.gridx = 0; // Cột đầu tiên
        constraints.gridy = 0; // Hàng đầu tiên
        constraints.insets = new Insets(30, 20, 30, 20); // Khoảng cách giữa các JPanel
        for (int i = 0; i < products.size(); i++) {
            Product p = products.get(i);
            JPanel pn = new JPanel();
            pn.setPreferredSize(new Dimension(250, 220));
            pn.setBackground(new java.awt.Color(255, 255, 255));
            pn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
            pn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            JLabel img = new JLabel();
            img.setBackground(new java.awt.Color(255, 255, 255));
            ImageIcon icon = new ImageIcon(getClass().getResource("/img/" + p.getImage()));
            img.setIcon(scaleIcon(icon, 190, 150)); // NOI18N
            img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            img.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            pn.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 190, 150));

            JButton btnSua = new JButton();
            btnSua.setBackground(Color.WHITE);
            btnSua.setCursor(new Cursor(Cursor.HAND_CURSOR));
            ImageIcon iconSua = new ImageIcon(getClass().getResource("/img/icons8-modify-64.png"));
            btnSua.setIcon(scaleIcon(iconSua, 40, 40)); // NOI18N
            pn.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 7, 40, 40));

            JButton btnXoa = new JButton();
            btnXoa.setBackground(Color.WHITE);
            btnXoa.setCursor(new Cursor(Cursor.HAND_CURSOR));
            ImageIcon iconXoa = new ImageIcon(getClass().getResource("/img/icons8-delete-64.png"));
            btnXoa.setIcon(scaleIcon(iconXoa, 40, 40)); // NOI18N
            pn.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 50, 40, 40));

            JLabel lblTen = new JLabel();
            lblTen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
            lblTen.setText(p.getName());
            pn.add(lblTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, 220, -1));

            JLabel lblSL = new JLabel();
            lblSL.setText("SL : " + p.getUnitInStock());
            lblSL.setFont(new java.awt.Font("Segoe UI", 0, 18));
            pn.add(lblSL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, -1));

            JLabel lblGia = new JLabel();
            lblGia.setText(formatter.format(p.getPrice()) + " đ");
            lblGia.setFont(new java.awt.Font("Segoe UI", 0, 18));
            pn.add(lblGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

            JLabel lblXu = new JLabel();
            ImageIcon iconXu = new ImageIcon(getClass().getResource("/img/icons8-coin-48.png"));
            lblXu.setIcon(scaleIcon(iconXu, 30, 30));
            pn.add(lblXu, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 188, 30, -1));
            if (i % 5 == 0) {
                constraints.gridx = 0;
                constraints.gridy++;
            }
            pDSSP.add(pn, constraints);
            constraints.gridx++;
            addEventSua(btnSua, p);
            addEventXoa(btnXoa, p);
            addEventHover(pn, new Color(210, 236, 245), Color.WHITE);
        }
    }

    private void addEventHover(JPanel panel, Color colorNew, Color colorOld) {
        panel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                panel.setBackground(colorNew); // Đổi màu nền khi hover vào
            }

            @Override
            public void mouseExited(MouseEvent e) {
                panel.setBackground(colorOld); // Đổi màu nền về mặc định khi rời khỏi
            }
        });
    }

    private void addEventSua(JButton btn, Product p) {
        btn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                productIdLocal = p.getProductId();
                fileSua = null;
                String type = categoryBUS.getCategoryById(p.getCategory().getCategoryId()).getName();
                txtTenSP1.setText(p.getName());
                cbbLoai1.setSelectedItem(type);
                txtSoLuong1.setText(p.getUnitInStock() + "");
                txtGia1.setText(p.getPrice() + "");
                jcbTT.setSelectedIndex(p.isStatus() == true ? 0 : 1);
                BufferedImage originalImage;
                try {
                    originalImage = ImageIO.read(getClass().getResource("/img/" + p.getImage()));
                    // Resize ảnh
                    Image resizedImage = originalImage.getScaledInstance(186, 136, Image.SCALE_SMOOTH);
                    // Tạo ImageIcon từ ảnh đã resize
                    ImageIcon imageIcon = new ImageIcon(resizedImage);
                    // Set ImageIcon cho JLabel
                    lblSuaAnh.setIcon(imageIcon);
                } catch (IOException ex) {
                    Logger.getLogger(TAB_SanPham.class.getName()).log(Level.SEVERE, null, ex);
                }
                modalSuaSP.setVisible(true);
            }
        });
    }

    private void addEventXoa(JButton btn, Product p) {
        btn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Bạn có chắc chắc muôn xóa sản phẩm này?", "Cảnh bảo", JOptionPane.YES_NO_OPTION)
                        == JOptionPane.YES_OPTION) {
                    if (productBUS.deteleProduct(p.getProductId())) {
                        JOptionPane.showMessageDialog(null, "Xóa sản phẩm thành công");
                        loadData("", "Tất cả", true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Xóa sản phẩm thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });
    }

    private void txtTimSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimSPActionPerformed

    private void txtTimSPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimSPKeyReleased
        // TODO add your handling code here:
        String txtSearch = txtTimSP.getText();
        String type = (String) cbbTim.getSelectedItem();
        boolean status = cbbTrangThai.getSelectedItem().equals("Đang bán");
        loadData(txtSearch, type, status);
    }//GEN-LAST:event_txtTimSPKeyReleased

    private void cbbTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTimActionPerformed
        // TODO add your handling code here:
        String txtSearch = txtTimSP.getText();
        String type = (String) cbbTim.getSelectedItem();
        boolean status = cbbTrangThai.getSelectedItem().equals("Đang bán");
        loadData(txtSearch, type, status);
    }//GEN-LAST:event_cbbTimActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        modalThemSP.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void txtGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        if (checkValid(txtTenSP, txtSoLuong, txtGia, false)) {
            String name = txtTenSP.getText();
            double price = Double.parseDouble(txtGia.getText());
            int unitInStock = Integer.parseInt(txtSoLuong.getText());
            String type = (String) cbbLoai.getSelectedItem();
            
            if(productBUS.existsByName(name)){
                JOptionPane.showMessageDialog(null, "Tên sản phẩm đã tồn tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String image = fileManager.createFile(fileThem);
            if (image == null) {
                JOptionPane.showMessageDialog(null, "Không phải file ảnh", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Product p = new Product(null, name, price, unitInStock, image, true, categoryBUS.getCategoryByName(type));
            if (productBUS.insertProduct(p)) {
                JOptionPane.showMessageDialog(null, "Thêm mới thành công");
                clearData();
                modalThemSP.setVisible(false);
                loadData("", "Tất cả", true);
            } else {
                JOptionPane.showMessageDialog(null, "Thêm mới thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling codue here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                fileThem = fileChooser.getSelectedFile();
                Image image = ImageIO.read(fileThem);
                ImageIcon icon = new ImageIcon(image.getScaledInstance(186, 136, Image.SCALE_SMOOTH));
                lblThemAnh.setIcon(icon);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtTenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSPActionPerformed

    private void txtSoLuong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuong1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuong1ActionPerformed

    private void txtGia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGia1ActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        if (checkValid(txtTenSP1, txtSoLuong1, txtGia1, true)) {
            String name = txtTenSP1.getText();
            double price = Double.parseDouble(txtGia1.getText());
            int unitInStock = Integer.parseInt(txtSoLuong1.getText());
            String type = (String) cbbLoai1.getSelectedItem();
            boolean status = jcbTT.getSelectedItem().equals("Đang bán");
            Product productOld = productBUS.getProductById(productIdLocal);
            if(!productOld.getName().equals(name) && productBUS.existsByName(name)){
                JOptionPane.showMessageDialog(null, "Tên sản phẩm đã tồn tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Product productNew;
            if (fileSua == null) { // Không update ảnh
                productNew = new Product(productIdLocal, name, price, unitInStock, productOld.getImage(), status, categoryBUS.getCategoryByName(type));
            } else {
                String image = fileManager.updateFile(fileSua, productOld.getImage());
                if (image == null) {
                    JOptionPane.showMessageDialog(null, "Không phải file ảnh", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                productNew = new Product(productIdLocal, name, price, unitInStock, image, status, categoryBUS.getCategoryByName(type));
            }
            if (productBUS.updateProduct(productNew)) {
                JOptionPane.showMessageDialog(null, "Cập nhật thành công");
                modalSuaSP.setVisible(false);
                cbbTrangThai.setSelectedIndex(0);
                loadData("", "Tất cả", true);
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                fileSua = fileChooser.getSelectedFile();
                Image image = ImageIO.read(fileSua);
                ImageIcon icon = new ImageIcon(image.getScaledInstance(186, 136, Image.SCALE_SMOOTH));
                lblSuaAnh.setIcon(icon);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtTenSP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSP1ActionPerformed

    private void cbbTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTrangThaiActionPerformed
        // TODO add your handling code here:
        String txtSearch = txtTimSP.getText();
        String type = (String) cbbTim.getSelectedItem();
        boolean status = cbbTrangThai.getSelectedItem().equals("Đang bán");
        loadData(txtSearch, type, status);
    }//GEN-LAST:event_cbbTrangThaiActionPerformed

    private void jcbTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cbbLoai;
    private javax.swing.JComboBox<String> cbbLoai1;
    private javax.swing.JComboBox<String> cbbTim;
    private javax.swing.JComboBox<String> cbbTrangThai;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPaneSP;
    private javax.swing.JComboBox<String> jcbTT;
    private javax.swing.JLabel ketQua;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblGia1;
    private javax.swing.JLabel lblLoai;
    private javax.swing.JLabel lblLoai1;
    private javax.swing.JLabel lblSuaAnh;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTen1;
    private javax.swing.JLabel lblThemAnh;
    private javax.swing.JDialog modalSuaSP;
    private javax.swing.JDialog modalThemSP;
    private javax.swing.JPanel pDSSP;
    private javax.swing.JPanel pRight;
    private javax.swing.JPanel pRight_Top;
    private javax.swing.JPanel pnThemAnh;
    private javax.swing.JPanel pnThemAnh1;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtGia1;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSoLuong1;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTenSP1;
    private javax.swing.JTextField txtTimSP;
    // End of variables declaration//GEN-END:variables
}
