/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.manager;

/**
 *
 * @author Hoang
 */
import bus.CustomerBUS;
import static connectDB.ConnectDB.con;
import entity.Customer;
import gui.custom.CustomComboBoxUI;
import gui.custom.CustomScrollBarUI;
import gui.custom.TableActionCellEditor;
import gui.custom.TableActionCellEditorOnlyEdit;
import gui.custom.TableActionCellRender;
import gui.custom.TableActionCellRenderOnlyEdit;
import gui.custom.TableActionEvent;
import gui.custom.TableActionEventOnlyEdit;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.lang.System.Logger.Level;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.List;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

public class TAB_KhachHang extends javax.swing.JPanel {

    private DefaultTableModel modelTable;
    private CustomerBUS customerBUS;
    private DecimalFormat df = new DecimalFormat("#,### đ");

    /**
     * Creates new form TAB_KhachHang
     */
    public TAB_KhachHang() {
        customerBUS = new bus.CustomerBUS();
        initComponents();
        
        TableActionEventOnlyEdit event = (int row) -> {
            fillCustomerToModal();
                modalEditKhachHang.setLocationRelativeTo(null);
                modalEditKhachHang.setVisible(true);
        };
        tableKhachHang.getColumnModel().getColumn(5).setCellRenderer(new TableActionCellRenderOnlyEdit());
        tableKhachHang.getColumnModel().getColumn(5).setCellEditor(new TableActionCellEditorOnlyEdit(event));
        setTieuChiTK(tieuChiTK1, chonThongKee);
        loadData(0, LocalDate.now().getYear());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modalEditKhachHang = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNameEdit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSdtEdit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmailEdit = new javax.swing.JTextField();
        btnSaveEdit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        pnRight = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableKhachHang = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        ketQua = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        tieuChiTK1 = new javax.swing.JComboBox<>();
        chonThongKee = new javax.swing.JComboBox<>();

        modalEditKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        modalEditKhachHang.setSize(new java.awt.Dimension(500, 450));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 450));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(725, 600));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Họ và Tên");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtNameEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNameEdit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Số điện thoại");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtSdtEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSdtEdit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Email");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtEmailEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmailEdit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        btnSaveEdit.setBackground(new java.awt.Color(11, 77, 163));
        btnSaveEdit.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnSaveEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveEdit.setText("Cập nhật");
        btnSaveEdit.setToolTipText("");
        btnSaveEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSaveEdit)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtSdtEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNameEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSdtEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnSaveEdit)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 255));
        jLabel14.setText("Sửa Thông Tin Khách Hàng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(95, 95, 95))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout modalEditKhachHangLayout = new javax.swing.GroupLayout(modalEditKhachHang.getContentPane());
        modalEditKhachHang.getContentPane().setLayout(modalEditKhachHangLayout);
        modalEditKhachHangLayout.setHorizontalGroup(
            modalEditKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        modalEditKhachHangLayout.setVerticalGroup(
            modalEditKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setMinimumSize(new java.awt.Dimension(1083, 765));
        pnRight.setName(""); // NOI18N
        pnRight.setPreferredSize(new java.awt.Dimension(1083, 765));
        pnRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        String[] header = {"Mã khách hàng","Tên khách hàng", "Số điện thoại", "Email","Chi tiêu trong kỳ", "Thao tác"};
        modelTable = new DefaultTableModel(header,0){
            boolean[] canEdit = new boolean [] {
                false,false, false,false,false, true
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        tableKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tableKhachHang.setModel(modelTable);
        tableKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableKhachHang.setGridColor(new java.awt.Color(255, 255, 255));
        tableKhachHang.setRowHeight(50);
        tableKhachHang.setSelectionBackground(new java.awt.Color(54,107,177));
        tableKhachHang.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableKhachHang.getTableHeader().setReorderingAllowed(false);
        tableKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKhachHangMouseClicked(evt);
            }
        });
        tableKhachHang.getTableHeader().setPreferredSize(new Dimension(tableKhachHang.getColumnModel().getTotalColumnWidth(), 50));
        tableKhachHang.getTableHeader().setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));
        tableKhachHang.getTableHeader().setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                label.addMouseListener(null);

                return label;
            }
        });
        jScrollPane2.setViewportView(tableKhachHang);
        TableColumnModel columnModel = tableKhachHang.getColumnModel();
        TableColumn id = columnModel.getColumn(0);
        TableColumn ten = columnModel.getColumn(1);
        TableColumn sdt = columnModel.getColumn(2);
        TableColumn email = columnModel.getColumn(3);
        TableColumn chiTieu = columnModel.getColumn(4);
        TableColumn thaoTac = columnModel.getColumn(5);

        id.setPreferredWidth(50);
        ten.setPreferredWidth(200);
        sdt.setPreferredWidth(120);
        email.setPreferredWidth(180);
        chiTieu.setPreferredWidth(200);
        thaoTac.setPreferredWidth(50);
        tableKhachHang.setGridColor(new java.awt.Color(255, 255, 255));

        tableKhachHang.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jScrollPane2.setViewportView(tableKhachHang);
        jScrollPane2.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        jScrollPane2.getHorizontalScrollBar().setUI(new CustomScrollBarUI());
        tableKhachHang.getTableHeader().setResizingAllowed(false);
        for (int i = 0; i < tableKhachHang.getColumnCount(); i++) {
            tableKhachHang.getColumnModel().getColumn(i).setResizable(false);
        }

        pnRight.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1520, 760));
        jScrollPane2.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        jScrollPane2.getHorizontalScrollBar().setUI(new CustomScrollBarUI());
        jScrollPane2.getViewport().setBackground(Color.WHITE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Kết quả:");
        pnRight.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 860, -1, -1));

        ketQua.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ketQua.setText("0");
        pnRight.add(ketQua, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 860, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        pnRight.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 30, 30));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        txtSearch.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        pnRight.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 260, -1));

        tieuChiTK1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tieuChiTK1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo năm", "Theo tháng"}));
        tieuChiTK1.setBorder(null);
        tieuChiTK1.setMinimumSize(new java.awt.Dimension(132, 40));
        tieuChiTK1.setPreferredSize(new java.awt.Dimension(132, 40));
        tieuChiTK1.setUI( new CustomComboBoxUI());
        tieuChiTK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tieuChiTK1ActionPerformed(evt);
            }
        });
        pnRight.add(tieuChiTK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 30, -1, 40));
        tieuChiTK1.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        chonThongKee = new JComboBox<>();
        chonThongKee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chonThongKee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ""}));
        chonThongKee.setMinimumSize(new java.awt.Dimension(132, 40));
        chonThongKee.setPreferredSize(new java.awt.Dimension(132, 40));
        chonThongKee.setUI( new CustomComboBoxUI());
        chonThongKee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonThongKeeActionPerformed(evt);
            }
        });
        pnRight.add(chonThongKee, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 30, -1, 40));
        chonThongKee.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        chonThongKee.setMaximumRowCount(3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fillCustomerToModal() {
        int selectedRow = tableKhachHang.getSelectedRow();
        Customer customer = customerBUS.getCustomerById(tableKhachHang.getValueAt(selectedRow, 0).toString());
        txtNameEdit.setText(customer.getName());
        txtSdtEdit.setText(customer.getPhone());
        txtEmailEdit.setText(customer.getEmail());
    }
    
        private boolean checkValid(String name, String phone, String email){
        if(name.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Tên không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(phone.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Số điện thoại không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(!phone.matches("^0[0-9]{9}$")){
            JOptionPane.showMessageDialog(null, "Số điện thoại phải bắt đầu bằng 0 và có 10 ký tự số", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(!email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")){
            JOptionPane.showMessageDialog(null, "Không đúng định dạng email", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }    
    
    private void setTieuChiTK(JComboBox tieuChi, JComboBox chon) {
        chon.removeAllItems();
        if (tieuChi.getSelectedIndex() == 0) {
            Calendar calendar = Calendar.getInstance();
            int currentYear = calendar.get(Calendar.YEAR);
            for (int i = 2020; i <= currentYear; i++) {
                chon.addItem("" + i);
            }
            chon.setSelectedItem(currentYear + "");
        } else {
            for (int i = 1; i <= 12; i++) {
                chon.addItem("Tháng " + i);
            }
            chon.setSelectedIndex(LocalDate.now().getMonthValue() - 1);
        }
    }    
    
    private void loadData(int month, int year) {
        modelTable.setRowCount(0);
        Map<Customer, Double> result = customerBUS.getTop10Customer(month, year);
        ketQua.setText(result.size() + "");
        for(Map.Entry<Customer,Double> entry : result.entrySet()){
            Customer customer = entry.getKey();
            modelTable.addRow(new Object[]{customer.getCustomerId(), customer.getName(), customer.getPhone(), customer.getEmail(),
            df.format(entry.getValue())});
        }
    }
    private void loadDataFindByKeyword(String keyword){
        modelTable.setRowCount(0);
        Map<Customer,Double> result = customerBUS.getCustomerByKeyword(keyword);
        ketQua.setText(result.size() + "");
        for(Map.Entry<Customer,Double> entry : result.entrySet()){
            Customer customer = entry.getKey();
            modelTable.addRow(new Object[]{customer.getCustomerId(), customer.getName(), customer.getPhone(), customer.getEmail(),
            df.format(entry.getValue())});
        }
    }

    private void tableKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKhachHangMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tableKhachHangMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String search = txtSearch.getText();
        loadDataFindByKeyword(search);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tieuChiTK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tieuChiTK1ActionPerformed
        // TODO add your handling code here:
        setTieuChiTK(tieuChiTK1, chonThongKee);
    }//GEN-LAST:event_tieuChiTK1ActionPerformed

    private void chonThongKeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonThongKeeActionPerformed
        // TODO add your handling code here:
        txtSearch.setText("");
        int select = chonThongKee.getSelectedIndex();
        if (select == -1) {
            return;
        }
        if (tieuChiTK1.getSelectedIndex() == 0) {
            int year = Integer.parseInt(chonThongKee.getItemAt(select));
            loadData(0, year);
        } else {
            int year = LocalDate.now().getYear();
            int month = chonThongKee.getSelectedIndex() + 1;
            loadData(month, year);
        }
    }//GEN-LAST:event_chonThongKeeActionPerformed

    private void btnSaveEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEditActionPerformed
        String name = txtNameEdit.getText();
        String phone = txtSdtEdit.getText();
        String email = txtEmailEdit.getText();
        int selectedRow = tableKhachHang.getSelectedRow();
        if (checkValid(name, phone, email)) {
            String CusId = tableKhachHang.getValueAt(selectedRow, 0).toString();
            Customer customerOld = customerBUS.getCustomerById(CusId);
            Customer customerNew;
            if (!phone.equals(customerOld.getPhone()) && customerBUS.getCustomerByPhone(phone) != null) {
                JOptionPane.showMessageDialog(null, "Số điện thoại đã tồn tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            customerNew = new Customer(CusId, name, phone, email);
            if (customerBUS.updateCustomer(customerNew)) {
                JOptionPane.showMessageDialog(null, "Cập nhật thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            loadData(LocalDate.now().getMonthValue(), LocalDate.now().getYear());
            txtSearch.setText("");
            modalEditKhachHang.setVisible(false);
        }
    }//GEN-LAST:event_btnSaveEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveEdit;
    private javax.swing.JComboBox<String> chonThongKee;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel ketQua;
    private javax.swing.JDialog modalEditKhachHang;
    private javax.swing.JPanel pnRight;
    private javax.swing.JTable tableKhachHang;
    private javax.swing.JComboBox<String> tieuChiTK1;
    private javax.swing.JTextField txtEmailEdit;
    private javax.swing.JTextField txtNameEdit;
    private javax.swing.JTextField txtSdtEdit;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
