/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.manager;

import bus.RoomBUS;
import bus.SeatBUS;
import bus.ShowtimeBUS;
import connectDB.ConnectDB;
import entity.Room;
import entity.Seat;
import entity.Showtime;
import enums.RoomStatus;
import enums.SeatType;
import gui.custom.CustomComboBoxUI;
import gui.custom.CustomScrollBarUI;
import gui.custom.TableActionCellEditor;
import gui.custom.TableActionCellEditorOnlyEdit;
import gui.custom.TableActionCellRender;
import gui.custom.TableActionCellRenderOnlyEdit;
import gui.custom.TableActionEvent;
import gui.custom.TableActionEventOnlyEdit;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Hoang
 */
public class TAB_Phong extends javax.swing.JPanel {

    private DefaultTableModel modelTable;
//    private int selectedRow;
    private RoomBUS roomBUS;
    private SeatBUS seatBUS;
    private ShowtimeBUS showtimeBUS;

    /**
     * Creates new form TAB_Phong
     */
    public TAB_Phong() {
        roomBUS = new RoomBUS();
        seatBUS = new SeatBUS();
        showtimeBUS = new ShowtimeBUS();
        initComponents();

        TableActionEventOnlyEdit event = (int row) -> {
            int selectedRow = tablePhong.getSelectedRow();
            Room room = roomBUS.getRoomById(tablePhong.getValueAt(selectedRow, 0).toString());
            txtTenPhong.setText(room.getName());
            cbTrangThai.setSelectedItem(room.getRoomStatus() == RoomStatus.ACTIVE ? "Đang hoạt động" : "Đang bảo trì");
            modalSuaPhong.setVisible(true);
            tablePhong.getCellEditor().stopCellEditing();
        };
        tablePhong.getColumnModel().getColumn(4).setCellRenderer(new TableActionCellRenderOnlyEdit());
        tablePhong.getColumnModel().getColumn(4).setCellEditor(new TableActionCellEditorOnlyEdit(event));
        loadData("Tất cả");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modalThemPhong = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        lblTen = new javax.swing.JLabel();
        lblSoGhe = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        txtTen = new javax.swing.JTextField();
        txtSoGhe = new javax.swing.JTextField();
        modalSuaPhong = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        lblTen1 = new javax.swing.JLabel();
        lblSoGhe1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCapNhat = new javax.swing.JButton();
        txtTenPhong = new javax.swing.JTextField();
        cbTrangThai = new javax.swing.JComboBox<>();
        modalChiTietPhong = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        pnRight = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePhong = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        ketQua = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cbSelectTrangThai = new javax.swing.JComboBox<>();

        modalThemPhong.setMinimumSize(new java.awt.Dimension(448, 347));
        modalThemPhong.setModal(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblTen.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTen.setText("Tên phòng");

        lblSoGhe.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblSoGhe.setText("Số lượng ghế");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("THÊM PHÒNG");

        btnThem.setBackground(new java.awt.Color(19, 87, 157));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtTen.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });

        txtSoGhe.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtSoGhe.setBorder(null);
        txtSoGhe.setEnabled(false);
        txtSoGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoGheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(138, 138, 138))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTen)
                    .addComponent(lblSoGhe))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSoGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnThem)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout modalThemPhongLayout = new javax.swing.GroupLayout(modalThemPhong.getContentPane());
        modalThemPhong.getContentPane().setLayout(modalThemPhongLayout);
        modalThemPhongLayout.setHorizontalGroup(
            modalThemPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modalThemPhongLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        modalThemPhongLayout.setVerticalGroup(
            modalThemPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        modalThemPhong.setLocationRelativeTo(null);
        modalThemPhong.setResizable(false);

        modalSuaPhong.setMinimumSize(new java.awt.Dimension(448, 347));
        modalSuaPhong.setModal(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblTen1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTen1.setText("Tên phòng");

        lblSoGhe1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblSoGhe1.setText("Trạng thái");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("SỬA PHÒNG");

        btnCapNhat.setBackground(new java.awt.Color(19, 87, 157));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnThem.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        txtTenPhong.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtTenPhong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTenPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenPhongActionPerformed(evt);
            }
        });

        cbTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang hoạt động", "Đang bảo trì" }));
        cbTrangThai.setBorder(null);
        cbTrangThai.setUI(new CustomComboBoxUI());
        cbTrangThai.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(138, 138, 138))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTen1)
                    .addComponent(lblSoGhe1))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTen1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTenPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoGhe1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnCapNhat)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout modalSuaPhongLayout = new javax.swing.GroupLayout(modalSuaPhong.getContentPane());
        modalSuaPhong.getContentPane().setLayout(modalSuaPhongLayout);
        modalSuaPhongLayout.setHorizontalGroup(
            modalSuaPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        modalSuaPhongLayout.setVerticalGroup(
            modalSuaPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        modalSuaPhong.setLocationRelativeTo(null);
        modalSuaPhong.setResizable(false);

        modalChiTietPhong.setMinimumSize(new java.awt.Dimension(1200, 1000));
        modalChiTietPhong.setModal(true);
        modalChiTietPhong.setLocationRelativeTo(null);

        jPanel9.setBackground(new java.awt.Color(243, 245, 247));
        jPanel9.setMinimumSize(new java.awt.Dimension(1200, 1000));
        jPanel9.setName(""); // NOI18N
        jPanel9.setVerifyInputWhenFocusTarget(false);

        jPanel14.setBackground(new java.awt.Color(232, 204, 179));
        jPanel14.setMinimumSize(new java.awt.Dimension(1200, 60));

        txtTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txtTitle.setText("Galaxy Cinema | Phòng 01 | Số ghế (160/160)");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtTitle)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel15.setBackground(new java.awt.Color(243, 245, 247));
        jPanel15.setMinimumSize(new java.awt.Dimension(900, 740));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setMinimumSize(new java.awt.Dimension(1130, 635));
        jPanel20.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1130, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel21.setBorder(BorderFactory.createLineBorder(new Color(10,139,5)));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel43.setText("Ghế thường");

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel22.setBorder(BorderFactory.createLineBorder(Color.RED));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel44.setText("Ghế vip");

        jPanel24.setBackground(new java.awt.Color(10, 139, 5));
        jPanel24.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel46.setText("Ghế đang chọn");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel46)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel43)
                        .addGap(57, 57, 57)
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout modalChiTietPhongLayout = new javax.swing.GroupLayout(modalChiTietPhong.getContentPane());
        modalChiTietPhong.getContentPane().setLayout(modalChiTietPhongLayout);
        modalChiTietPhongLayout.setHorizontalGroup(
            modalChiTietPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        modalChiTietPhongLayout.setVerticalGroup(
            modalChiTietPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modalChiTietPhongLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setMinimumSize(new java.awt.Dimension(1083, 765));
        pnRight.setName(""); // NOI18N
        pnRight.setPreferredSize(new java.awt.Dimension(1083, 765));
        pnRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        String[] header = {"Mã phòng","Tên phòng", "Số lượng ghế", "Trạng thái", "Thao tác"};
        modelTable = new DefaultTableModel(header,0){
            boolean[] canEdit = new boolean [] {
                false,false, false,false, true
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        tablePhong.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tablePhong.setModel(modelTable);
        tablePhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablePhong.setGridColor(new java.awt.Color(255, 255, 255));
        tablePhong.setRowHeight(50);
        tablePhong.setSelectionBackground(new java.awt.Color(54,107,177));
        tablePhong.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePhong.getTableHeader().setReorderingAllowed(false);
        tablePhong.getTableHeader().setPreferredSize(new Dimension(tablePhong.getColumnModel().getTotalColumnWidth(), 50));
        tablePhong.getTableHeader().setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        tablePhong.getTableHeader().setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                label.addMouseListener(null);

                return label;
            }
        });
        tablePhong.getTableHeader().setFont(new Font("Segoe UI", 0 , 16));
        tablePhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePhongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePhong);
        TableColumnModel columnModel = tablePhong.getColumnModel();
        TableColumn idPhong = columnModel.getColumn(0);
        TableColumn tenPhong = columnModel.getColumn(1);
        TableColumn soLuongGhe = columnModel.getColumn(2);
        TableColumn trangThai = columnModel.getColumn(3);
        TableColumn thaoTac = columnModel.getColumn(4);

        idPhong.setPreferredWidth(50);
        tenPhong.setPreferredWidth(200);
        soLuongGhe.setPreferredWidth(120);
        trangThai.setPreferredWidth(120);
        thaoTac.setPreferredWidth(50);

        tablePhong.getTableHeader().setResizingAllowed(false);
        for (int i = 0; i < tablePhong.getColumnCount(); i++) {
            tablePhong.getColumnModel().getColumn(i).setResizable(false);
        }

        pnRight.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1540, 750));
        jScrollPane2.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        jScrollPane2.getHorizontalScrollBar().setUI(new CustomScrollBarUI());
        jScrollPane2.getViewport().setBackground(Color.WHITE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Kết quả:");
        pnRight.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 850, -1, -1));

        ketQua.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ketQua.setText("10");
        pnRight.add(ketQua, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 850, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        pnRight.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(19, 87, 157));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm phòng");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnRight.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 20, 190, 50));

        cbSelectTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 20));
        cbSelectTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đang hoạt động", "Đang bảo trì" }));
        cbSelectTrangThai.setBorder(null);
        cbSelectTrangThai.setUI(new CustomComboBoxUI());
        cbSelectTrangThai.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cbSelectTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelectTrangThaiActionPerformed(evt);
            }
        });
        pnRight.add(cbSelectTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 280, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 1690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadSeat(Room room) {
        List<Seat> seats = seatBUS.getSeatByRoom(room.getRoomId());
        txtTitle.setText("Galaxy Cinema | " + room.getName() + " | Số ghế (" + seats.size() + "/160)");
        jPanel20.removeAll();
        jPanel20.revalidate();
        jPanel20.repaint();
        jPanel20.setLayout(new GridLayout(10, 16, 10, 10));
        jPanel20.setBackground(new Color(243, 245, 247));
        for (int i = 0; i < seats.size(); i++) {
            Seat seat = seats.get(i);
            JPanel subPanel = new JPanel();
            subPanel.setLayout(new GridBagLayout());
            subPanel.setPreferredSize(new Dimension(60, 60));
            subPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            subPanel.setBackground(new Color(243, 245, 247));
            if (seat.getSeatType() == SeatType.STANDARD) {
                subPanel.setBorder(BorderFactory.createLineBorder(new Color(10, 139, 5)));
            } else {
                subPanel.setBorder(BorderFactory.createLineBorder(Color.RED));
            }
            JLabel lblNameSeat = new JLabel(seat.getName());
            lblNameSeat.setFont(new java.awt.Font("Segoe UI", 1, 18));
            subPanel.add(lblNameSeat);
            jPanel20.add(subPanel);
        }
    }

    private void loadData(String status) {
//        modelTable.getDataVector().removeAllElements();
        modelTable.setRowCount(0);
        List<Room> rooms = roomBUS.getRoomByStatus(status);
        ketQua.setText(rooms.size() + "");
        rooms.forEach(room -> {
            modelTable.addRow(new Object[]{room.getRoomId(), room.getName(), room.getSeatQuantity(),
                room.getRoomStatus() == RoomStatus.ACTIVE ? "Đang hoạt động" : "Đang bảo trì"});
        });
    }


    private void tablePhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePhongMouseClicked
        // TODO add your handling code here:
        int selectedRow = tablePhong.getSelectedRow();
        Room room = roomBUS.getRoomById(tablePhong.getValueAt(selectedRow, 0).toString());
        loadSeat(room);
        modalChiTietPhong.setVisible(true);
    }//GEN-LAST:event_tablePhongMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtSoGhe.setText("160");
        txtSoGhe.setEditable(false);
        modalThemPhong.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbSelectTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelectTrangThaiActionPerformed
        // TODO add your handling code here:
        loadData((String) cbSelectTrangThai.getSelectedItem());
    }//GEN-LAST:event_cbSelectTrangThaiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        String name = txtTen.getText();
        if (name.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Tên phòng không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(roomBUS.getRoomByName(name) != null){
            JOptionPane.showMessageDialog(null, "Tên phòng đã tồn tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String seatQuantity = txtSoGhe.getText();
        Room room = new Room(null, name, Integer.parseInt(seatQuantity), RoomStatus.ACTIVE);
        Room roomInsert = roomBUS.insertRoom(room);
        if (roomInsert != null) {
            for (int i = 65; i <= 74; i++) {
                for (int j = 1; j <= 16; j++) {
                    Seat seat = new Seat(null, j, String.valueOf((char) i), null, roomInsert);
                    if (i >= 68 && i <= 71) {
                        seat.setSeatType(SeatType.VIP);
                    } else {
                        seat.setSeatType(SeatType.STANDARD);
                    }
                    seatBUS.insertSeat(seat);
                }
            }
            JOptionPane.showMessageDialog(null, "Thêm mới phòng thành công");
            loadData("Tất cả");
        } else {
            JOptionPane.showMessageDialog(null, "Thêm mới phòng thất bại");
        }
        txtTen.setText("");
        modalThemPhong.setVisible(false);
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void txtSoGheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoGheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoGheActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        int selectedRow = tablePhong.getSelectedRow();
        Room room = roomBUS.getRoomById(tablePhong.getValueAt(selectedRow, 0).toString());
        String name = txtTenPhong.getText();
        if (name.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Tên phòng không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!room.getName().equals(name) && roomBUS.getRoomByName(name) != null){
            JOptionPane.showMessageDialog(null, "Tên phòng đã tồn tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String status = (String) cbTrangThai.getSelectedItem();
        RoomStatus roomStatus = status.equals("Đang hoạt động") ? RoomStatus.ACTIVE : RoomStatus.MAINTENANCE;
        if (roomStatus == RoomStatus.MAINTENANCE) {
            // Nếu chuyển sang bảo trì phải kiểm tra xem có suất chiếu trong tương lai không?
            // Nếu không có -> cho update
            // Nếu có  -> Không cho update
            if (showtimeBUS.checkShowtimeByPhong(room.getRoomId())) {
                JOptionPane.showMessageDialog(null, "Phòng đang có suất chiếu trong tương lai", "Lỗi", JOptionPane.ERROR_MESSAGE);
                txtTenPhong.setText("");
                modalSuaPhong.setVisible(false);
                return;
            }
        }
        room.setName(name);
        room.setRoomStatus(roomStatus);
        if (roomBUS.updateRoom(room)) {
            JOptionPane.showMessageDialog(null, "Cập nhật thành công");
            loadData("Tất cả");
        } else {
            JOptionPane.showMessageDialog(null, "Cập nhật thất bại");
        }
        txtTenPhong.setText("");
        modalSuaPhong.setVisible(false);
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void txtTenPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenPhongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cbSelectTrangThai;
    private javax.swing.JComboBox<String> cbTrangThai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel ketQua;
    private javax.swing.JLabel lblSoGhe;
    private javax.swing.JLabel lblSoGhe1;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTen1;
    private javax.swing.JDialog modalChiTietPhong;
    private javax.swing.JDialog modalSuaPhong;
    private javax.swing.JDialog modalThemPhong;
    private javax.swing.JPanel pnRight;
    private javax.swing.JTable tablePhong;
    private javax.swing.JTextField txtSoGhe;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenPhong;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
