/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.manager;

/**
 *
 * @author Hoang
 */
import bus.StaffBUS;
import com.itextpdf.text.log.SysoLogger;
import connectDB.ConnectDB;
import java.sql.SQLException;
import entity.Staff;
import enums.Role;
import gui.custom.CustomComboBoxUI;
import gui.custom.CustomScrollBarUI;
import gui.custom.TableActionCellEditor;
import gui.custom.TableActionCellEditorOnlyEdit;
import gui.custom.TableActionCellRender;
import gui.custom.TableActionCellRenderOnlyEdit;
import gui.custom.TableActionEvent;
import gui.custom.TableActionEventOnlyEdit;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

public class TAB_NhanSu extends javax.swing.JPanel {

    private StaffBUS staffBUS;
    private DefaultTableModel modelTable;
    private DecimalFormat df = new DecimalFormat("#,### đ");
    private DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy");

    /**
     * Creates new form TAB_NhanSu
     */
    public TAB_NhanSu() {
        staffBUS = new StaffBUS();
        initComponents();

        TableActionEventOnlyEdit event = (int row) -> {
            fillStaffDetail();
            modalSuaNhanVien.setLocationRelativeTo(null);
            modalSuaNhanVien.setVisible(true);
        };
        tableNhanVien.getColumnModel().getColumn(7).setCellRenderer(new TableActionCellRenderOnlyEdit());
        tableNhanVien.getColumnModel().getColumn(7).setCellEditor(new TableActionCellEditorOnlyEdit(event));
        setTieuChiTK(tieuChiTK, chonThongKe);
        loadData(0, LocalDate.now().getYear());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modalSuaNhanVien = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        txtSDT1 = new javax.swing.JTextField();
        txtEmail1 = new javax.swing.JTextField();
        comboGioiTinh1 = new javax.swing.JComboBox<>();
        btnSave1 = new javax.swing.JButton();
        ngayBatDau1 = new com.toedter.calendar.JDateChooser();
        txtChucVu1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        modalThemNhanVien = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jcbGioiTinh = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtTK = new javax.swing.JTextField();
        txtMK = new javax.swing.JPasswordField();
        txtNLMK = new javax.swing.JPasswordField();
        btnThemMoi = new javax.swing.JToggleButton();
        jDateNVL1 = new com.toedter.calendar.JDateChooser();
        pnRight = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableNhanVien = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        ketQua = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        tieuChiTK = new javax.swing.JComboBox<>();
        chonThongKe = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        modalSuaNhanVien.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        modalSuaNhanVien.setTitle("Sửa nhân viên");
        modalSuaNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        modalSuaNhanVien.setModal(true);
        modalSuaNhanVien.setSize(new java.awt.Dimension(638, 640));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(721, 660));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(721, 660));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("Họ và Tên");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel28.setText("Số điện thoại");
        jLabel28.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel29.setText("Giới tính");
        jLabel29.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel30.setText("Chức vụ");
        jLabel30.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel31.setText("Email");
        jLabel31.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel32.setText("Ngày bắt đầu");
        jLabel32.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtName1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtName1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        txtSDT1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtSDT1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        txtEmail1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtEmail1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        comboGioiTinh1.setUI(new gui.custom.CustomComboBoxUI());
        comboGioiTinh1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        comboGioiTinh1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        comboGioiTinh1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        btnSave1.setBackground(new java.awt.Color(19, 87, 157));
        btnSave1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnSave1.setForeground(new java.awt.Color(255, 255, 255));
        btnSave1.setText("Lưu");
        btnSave1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });

        ngayBatDau1.setBackground(new java.awt.Color(255, 255, 255));
        ngayBatDau1.setDateFormatString("dd/MM/yyyy");
        ngayBatDau1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtChucVu1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtChucVu1.setBorder(null);
        txtChucVu1.setEditable(false);
        txtChucVu1.setEnabled(false);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel33.setText("Tài khoản");

        txtTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtTaiKhoan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel33)
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ngayBatDau1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(comboGioiTinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSDT1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtChucVu1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel30))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel31)
                        .addComponent(jLabel28)
                        .addComponent(jLabel29)
                        .addComponent(jLabel6)))
                .addGap(40, 40, 40))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboGioiTinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChucVu1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngayBatDau1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnSave1)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout modalSuaNhanVienLayout = new javax.swing.GroupLayout(modalSuaNhanVien.getContentPane());
        modalSuaNhanVien.getContentPane().setLayout(modalSuaNhanVienLayout);
        modalSuaNhanVienLayout.setHorizontalGroup(
            modalSuaNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        modalSuaNhanVienLayout.setVerticalGroup(
            modalSuaNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );

        modalThemNhanVien.setTitle("Thêm nhân viên");
        modalThemNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        modalThemNhanVien.setLocationByPlatform(true);
        modalThemNhanVien.setMinimumSize(new java.awt.Dimension(682, 805));
        modalThemNhanVien.setModal(true);
        modalThemNhanVien.setPreferredSize(new java.awt.Dimension(682, 805));
        modalThemNhanVien.setLocationRelativeTo(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(682, 805));
        jPanel2.setPreferredSize(new java.awt.Dimension(682, 805));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Thông tin cơ bản");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setText("Họ và tên");

        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtTen.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        jcbGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jcbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jcbGioiTinh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        jcbGioiTinh.setUI(new CustomComboBoxUI());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setText("Giới tính");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setText("Số điện thoại");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setText("Email");

        txtsdt.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtsdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel12.setText("Ngày bắt đầu");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setText("Tài khoản đăng nhập");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel20.setText("Tài khoản");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel21.setText("Mật khẩu");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel22.setText("Nhập lại");

        txtTK.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtTK.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        txtMK.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtNLMK.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        btnThemMoi.setBackground(new java.awt.Color(19, 87, 157));
        btnThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnThemMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        jDateNVL1.setBackground(new java.awt.Color(255, 255, 255));
        jDateNVL1.setBorder(new javax.swing.border.MatteBorder(null));
        jDateNVL1.setDateFormatString("dd/MM/yyyy");
        jDateNVL1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jDateNVL1.setDate(java.sql.Date.valueOf(LocalDate.now()));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel9)
                        .addGap(30, 30, 30)
                        .addComponent(jcbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel10)
                        .addGap(30, 30, 30)
                        .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel11))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jDateNVL1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel20)
                        .addGap(30, 30, 30)
                        .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel21)
                        .addGap(32, 32, 32)
                        .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel22)
                        .addGap(32, 32, 32)
                        .addComponent(txtNLMK, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addComponent(btnThemMoi)))
                .addGap(620, 620, 620))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel9))
                    .addComponent(jcbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10))
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11)))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jDateNVL1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel19)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel20))
                    .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel21))
                    .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel22))
                    .addComponent(txtNLMK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnThemMoi)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        txtMK.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        txtNLMK.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        javax.swing.GroupLayout modalThemNhanVienLayout = new javax.swing.GroupLayout(modalThemNhanVien.getContentPane());
        modalThemNhanVien.getContentPane().setLayout(modalThemNhanVienLayout);
        modalThemNhanVienLayout.setHorizontalGroup(
            modalThemNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        modalThemNhanVienLayout.setVerticalGroup(
            modalThemNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setMinimumSize(new java.awt.Dimension(1083, 765));
        pnRight.setName(""); // NOI18N
        pnRight.setPreferredSize(new java.awt.Dimension(1083, 765));
        pnRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        String[] header = {"Mã nhân viên","Tên nhân viên", "Giới tính", "Số điện thoại","Email","Ngày bắt đầu", "Doanh số","Thao tác"};
        modelTable = new DefaultTableModel(header,0){
            boolean[] canEdit = new boolean [] {
                false,false, false,false,false,false,false, true
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        tableNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tableNhanVien.setModel(modelTable);
        tableNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableNhanVien.setGridColor(new java.awt.Color(255, 255, 255));
        tableNhanVien.setRowHeight(50);
        tableNhanVien.setSelectionBackground(new java.awt.Color(54,107,177));
        tableNhanVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableNhanVien.getTableHeader().setReorderingAllowed(false);
        tableNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNhanVienMouseClicked(evt);
            }
        });
        tableNhanVien.getTableHeader().setPreferredSize(new Dimension(tableNhanVien.getColumnModel().getTotalColumnWidth(), 50));
        tableNhanVien.getTableHeader().setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));
        tableNhanVien.getTableHeader().setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                label.addMouseListener(null);

                return label;
            }
        });
        jScrollPane2.setViewportView(tableNhanVien);
        TableColumnModel columnModel = tableNhanVien.getColumnModel();
        //TableColumn id = columnModel.getColumn(0);
        //TableColumn ten = columnModel.getColumn(1);
        //TableColumn sdt = columnModel.getColumn(2);
        TableColumn email = columnModel.getColumn(4);
        TableColumn doanhSo = columnModel.getColumn(6);
        //TableColumn thaoTac = columnModel.getColumn(5);
        //
        //id.setPreferredWidth(50);
        //ten.setPreferredWidth(200);
        //sdt.setPreferredWidth(120);
        email.setPreferredWidth(180);
        //chiTieu.setPreferredWidth(200);
        //thaoTac.setPreferredWidth(50);
        doanhSo.setPreferredWidth(120);
        tableNhanVien.setGridColor(new java.awt.Color(255, 255, 255));
        tableNhanVien.setGridColor(new java.awt.Color(255, 255, 255));
        tableNhanVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jScrollPane2.setViewportView(tableNhanVien);
        jScrollPane2.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        jScrollPane2.getHorizontalScrollBar().setUI(new CustomScrollBarUI());
        tableNhanVien.getTableHeader().setResizingAllowed(false);
        for (int i = 0; i < tableNhanVien.getColumnCount(); i++) {
            tableNhanVien.getColumnModel().getColumn(i).setResizable(false);
        }

        pnRight.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1540, 790));
        jScrollPane2.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        jScrollPane2.getHorizontalScrollBar().setUI(new CustomScrollBarUI());
        jScrollPane2.getViewport().setBackground(Color.WHITE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Kết quả:");
        pnRight.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 870, -1, -1));

        ketQua.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ketQua.setText("0");
        pnRight.add(ketQua, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 870, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        pnRight.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        txtSearch.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));
        pnRight.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 260, -1));

        tieuChiTK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tieuChiTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo năm", "Theo tháng"}));
        tieuChiTK.setBorder(null);
        tieuChiTK.setMinimumSize(new java.awt.Dimension(132, 40));
        tieuChiTK.setPreferredSize(new java.awt.Dimension(132, 40));
        tieuChiTK.setUI( new CustomComboBoxUI());
        tieuChiTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tieuChiTKActionPerformed(evt);
            }
        });
        pnRight.add(tieuChiTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 20, -1, 40));
        tieuChiTK.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

        chonThongKe = new JComboBox<>();
        chonThongKe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chonThongKe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ""}));
        chonThongKe.setMinimumSize(new java.awt.Dimension(132, 40));
        chonThongKe.setPreferredSize(new java.awt.Dimension(132, 40));
        chonThongKe.setUI( new CustomComboBoxUI());
        chonThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonThongKeActionPerformed(evt);
            }
        });
        pnRight.add(chonThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 20, -1, 40));
        chonThongKe.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));
        chonThongKe.setMaximumRowCount(3);

        jButton1.setBackground(new java.awt.Color(19, 87, 157));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnRight.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 1608, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fillStaffDetail() {
        int index = tableNhanVien.getSelectedRow();
        String staffId = tableNhanVien.getValueAt(index, 0).toString();
        Staff staff = staffBUS.getStaffById(staffId);
        txtName1.setText(staff.getName());
        txtSDT1.setText(staff.getPhone());
        txtEmail1.setText(staff.getEmail());
        comboGioiTinh1.setSelectedIndex(staff.isGender() == true ? 0 : 1);
        txtChucVu1.setText(" Nhân viên");
        txtTaiKhoan.setText(staff.getUsername());
        Date date = Date.from(staff.getStartingDate().atStartOfDay(ZoneId.systemDefault()).toInstant());
        ngayBatDau1.setDate(date);

    }

    private void loadData(int month, int year) {
        modelTable.setRowCount(0);
        Map<Staff, Double> result = staffBUS.getTop10Staff(month, year);
        ketQua.setText(result.size() + "");
        for (Map.Entry<Staff, Double> entry : result.entrySet()) {
            Staff s = entry.getKey();
            modelTable.addRow(new Object[]{s.getStaffId(), s.getName(), s.isGender() ? "Nam" : "Nữ", s.getPhone(),
                s.getEmail(), dtf.format(s.getStartingDate()), df.format(entry.getValue())});
        }
    }

    private void setTieuChiTK(JComboBox tieuChi, JComboBox chon) {
        chon.removeAllItems();
        if (tieuChi.getSelectedIndex() == 0) {
            Calendar calendar = Calendar.getInstance();
            int currentYear = calendar.get(Calendar.YEAR);
            for (int i = 2020; i <= currentYear; i++) {
                chon.addItem("" + i);
            }
            chon.setSelectedItem(currentYear + "");
        } else {
            for (int i = 1; i <= 12; i++) {
                chon.addItem("Tháng " + i);
            }
            chon.setSelectedIndex(LocalDate.now().getMonthValue() - 1);
        }
    }
    private void tableNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNhanVienMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNhanVienMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed
    private void loadDataFindByKeyword(String keyword) {
        modelTable.setRowCount(0);
        Map<Staff, Double> result = staffBUS.getStaffByKeyword(keyword);
        ketQua.setText(result.size() + "");
        for (Map.Entry<Staff, Double> entry : result.entrySet()) {
            Staff s = entry.getKey();
            modelTable.addRow(new Object[]{s.getStaffId(), s.getName(), s.isGender() ? "Nam" : "Nữ", s.getPhone(),
                s.getEmail(), dtf.format(s.getStartingDate()), df.format(entry.getValue())});
        }
    }
    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String search = txtSearch.getText();
        if (search.trim().equals("")) {
            tieuChiTK.setSelectedIndex(0);
            chonThongKe.setSelectedItem(LocalDate.now().getYear() + "");
        }
        loadDataFindByKeyword(search);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tieuChiTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tieuChiTKActionPerformed
        // TODO add your handling code here:
        setTieuChiTK(tieuChiTK, chonThongKe);
    }//GEN-LAST:event_tieuChiTKActionPerformed

    private void chonThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonThongKeActionPerformed
        // TODO add your handling code here:
        txtSearch.setText("");
        int select = chonThongKe.getSelectedIndex();
        if (select == -1) {
            return;
        }
        if (tieuChiTK.getSelectedIndex() == 0) {
            int year = Integer.parseInt(chonThongKe.getItemAt(select));
            loadData(0, year);
        } else {
            int year = LocalDate.now().getYear();
            int month = chonThongKe.getSelectedIndex() + 1;
            loadData(month, year);
        }
    }//GEN-LAST:event_chonThongKeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        modalThemNhanVien.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    private boolean checkValid() {
        String name = txtName1.getText().trim();
        String phone = txtSDT1.getText().trim();
        String email = txtEmail1.getText().trim();
        String username = txtTaiKhoan.getText().trim();
        LocalDate startDate = ngayBatDau1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Họ tên không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtName1.requestFocus();
            return false;
        }
        if (!(phone.matches("^(03|05|07|08|09)\\d{8}$"))) {
            JOptionPane.showMessageDialog(null, "Error: Số điện thoại phải đủ 10 số và bắt đầu bằng 03, 05, 07, 08 hoặc 09!",
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtSDT1.requestFocus();
            return false;
        }
        if (!(email.matches("^[a-zA-Z0-9]+@[a-zA-Z]+\\.com$"))) {
            JOptionPane.showMessageDialog(null, "Error: Email không đúng định dạng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtEmail1.requestFocus();
            return false;
        }
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tài khoản không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtTaiKhoan.requestFocus();
            return false;
        }
        if (startDate.isAfter(LocalDate.now())) {
            JOptionPane.showMessageDialog(null, "Error: Ngày vào làm phải trước hoặc là ngày hiện tại!");
            ngayBatDau1.requestFocus();
            return false;
        }
        return true;
    }
    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        int index = tableNhanVien.getSelectedRow();
        String staffId = tableNhanVien.getValueAt(index, 0).toString();
        if (checkValid()) {
            String name = txtName1.getText().trim();
            String phone = txtSDT1.getText().trim();
            String email = txtEmail1.getText().trim();
            String username = txtTaiKhoan.getText().trim();
            LocalDate startDate = ngayBatDau1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            boolean gender = comboGioiTinh1.getSelectedItem().equals("Nam");
            Staff staff = staffBUS.getStaffById(staffId);
            staff.setName(name);
            staff.setPhone(phone);
            staff.setEmail(email);
            staff.setUsername(username);
            staff.setStartingDate(startDate);
            staff.setGender(gender);
            if (staffBUS.updateStaff(staff)) {
                JOptionPane.showMessageDialog(null, "Cập nhật thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            loadData(0, LocalDate.now().getYear());
            txtSearch.setText("");
            modalSuaNhanVien.setVisible(false);
        }
    }//GEN-LAST:event_btnSave1ActionPerformed
    private boolean checkValidAdd() {
        String name = txtTen.getText().trim();
        String phone = txtsdt.getText().trim();
        String email = txtEmail.getText().trim();
        LocalDate startDate = jDateNVL1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        String username = txtTK.getText().trim();
        String password = new String(txtMK.getPassword());
        String retypePassword = new String(txtNLMK.getPassword());
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Họ tên không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtTen.requestFocus();
            return false;
        }
        if (!(phone.matches("^(03|05|07|08|09)\\d{8}$"))) {
            JOptionPane.showMessageDialog(null, "Error: Số điện thoại phải đủ 10 số và bắt đầu bằng 03, 05, 07, 08 hoặc 09!",
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtsdt.requestFocus();
            return false;
        }
        if (!(email.matches("^[a-zA-Z0-9]+@[a-zA-Z]+\\.com$"))) {
            JOptionPane.showMessageDialog(null, "Error: Email không đúng định dạng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtEmail.requestFocus();
            return false;
        }

        if (startDate.isAfter(LocalDate.now())) {
            JOptionPane.showMessageDialog(null, "Error: Ngày vào làm phải trước hoặc là ngày hiện tại!");
            jDateNVL1.requestFocus();
            return false;
        }
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tài khoản không được rỗng", "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtTaiKhoan.requestFocus();
            return false;
        }
        if (staffBUS.getStaffUsername(username) != null) {
            JOptionPane.showMessageDialog(null, "Tài khoản đăng nhập đã tồn tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtTaiKhoan.requestFocus();
            return false;
        }
        if (!(password.matches("^(?=.*[0-9])(?=.*[A-Z])(?=.*[!@#$%^&*()]).{6,}$"))) {
            JOptionPane.showMessageDialog(null, "Error: Mật khẩu mới phải có từ 6 ký tự trở lên, có ít nhất 1 ký tự số, 1 ký tự in hoa, 1 ký tự đặc biệt!",
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtMK.requestFocus();
            return false;
        }
        if (!password.equals(retypePassword)) {
            JOptionPane.showMessageDialog(null, "Mật khẩu không giống nhau",
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtNLMK.requestFocus();
            return false;
        }
        return true;
    }

    public void clearData() {
        txtTen.setText("");
        jcbGioiTinh.setSelectedIndex(0);
        txtsdt.setText("");
        txtEmail.setText("");
        jDateNVL1.setDate(java.sql.Date.valueOf(LocalDate.now()));
        txtTK.setText("");
        txtMK.setText("");
        txtNLMK.setText("");
    }
    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        // TODO add your handling code here:
        if (checkValidAdd()) {
            String name = txtTen.getText().trim();
            String phone = txtsdt.getText().trim();
            String email = txtEmail.getText().trim();
            LocalDate startDate = jDateNVL1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            String username = txtTK.getText().trim();
            String password = new String(txtMK.getPassword());
            boolean gender = jcbGioiTinh.getSelectedItem().equals("Nam");
            Role role = Role.STAFF;
            Staff staff = new Staff(null, name, username, password, phone, gender, startDate, role, email);
            if (staffBUS.insertStaff(staff)) {
                JOptionPane.showMessageDialog(null, "Thêm mới thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Thêm mới thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            clearData();
            loadData(0, LocalDate.now().getYear());
            txtSearch.setText("");
            modalThemNhanVien.setVisible(false);
        }
    }//GEN-LAST:event_btnThemMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave1;
    private javax.swing.JToggleButton btnThemMoi;
    private javax.swing.JComboBox<String> chonThongKe;
    private javax.swing.JComboBox<String> comboGioiTinh1;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateNVL1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbGioiTinh;
    private javax.swing.JLabel ketQua;
    private javax.swing.JDialog modalSuaNhanVien;
    private javax.swing.JDialog modalThemNhanVien;
    private com.toedter.calendar.JDateChooser ngayBatDau1;
    private javax.swing.JPanel pnRight;
    private javax.swing.JTable tableNhanVien;
    private javax.swing.JComboBox<String> tieuChiTK;
    private javax.swing.JTextField txtChucVu1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JPasswordField txtMK;
    private javax.swing.JPasswordField txtNLMK;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtSDT1;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTK;
    private javax.swing.JTextField txtTaiKhoan;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables

}
